// apps/svelte-demos/demo-svelte-skip/src/SelectPlanStep.svelte
<script lang="ts">
  import { usePathContext } from "@daltonr/pathwrite-svelte";
  import type { SubscriptionData } from "./subscription";

  const ctx = usePathContext<SubscriptionData>();
  let errors = $derived(ctx.snapshot?.hasAttemptedNext ? ctx.snapshot.fieldErrors : {});
</script>

{#if ctx.snapshot}
  {@const data = ctx.snapshot.data}
  <div class="form-body">
    <p class="step-intro">Choose the plan that's right for you. Free gets you started — upgrade anytime.</p>

    <div class="plan-options">
      <label class="plan-card" class:plan-card--selected={data.plan === "free"}>
        <input
          type="radio"
          name="plan"
          value="free"
          checked={data.plan === "free"}
          onchange={() => ctx.setData("plan", "free")}
        />
        <div class="plan-card__body">
          <span class="plan-card__name">Free</span>
          <span class="plan-card__price">$0 / month</span>
          <ul class="plan-card__features">
            <li>1 project</li>
            <li>Community support</li>
            <li>Basic analytics</li>
          </ul>
        </div>
      </label>

      <label class="plan-card" class:plan-card--selected={data.plan === "paid"}>
        <input
          type="radio"
          name="plan"
          value="paid"
          checked={data.plan === "paid"}
          onchange={() => ctx.setData("plan", "paid")}
        />
        <div class="plan-card__body">
          <span class="plan-card__name">Pro</span>
          <span class="plan-card__price">$29 / month</span>
          <ul class="plan-card__features">
            <li>Unlimited projects</li>
            <li>Priority support</li>
            <li>Advanced analytics</li>
            <li>Custom branding</li>
          </ul>
        </div>
      </label>
    </div>

    {#if errors.plan}<span class="field-error">{errors.plan}</span>{/if}
    {#if data.plan === "free"}<p class="plan-note">
        ℹ️ Free plan — payment and billing steps will be skipped.
      </p>{/if}
  </div>
{/if}

// apps/react-demos/demo-react-skip/src/SelectPlanStep.tsx
import { usePathContext } from "@daltonr/pathwrite-react";
import type { SubscriptionData } from "./subscription";

export function SelectPlanStep() {
  const { snapshot, setData } = usePathContext<SubscriptionData>();
  const snap   = snapshot!;
  const data   = snap.data;
  const errors = snap.hasAttemptedNext ? snap.fieldErrors : {};

  return (
    <div className="form-body">
      <p className="step-intro">Choose the plan that's right for you. Free gets you started — upgrade anytime.</p>

      <div className="plan-options">
        <label className={`plan-card ${data.plan === "free" ? "plan-card--selected" : ""}`}>
          <input type="radio" name="plan" value="free" checked={data.plan === "free"} onChange={() => setData("plan", "free")} />
          <div className="plan-card__body">
            <span className="plan-card__name">Free</span>
            <span className="plan-card__price">$0 / month</span>
            <ul className="plan-card__features">
              <li>1 project</li><li>Community support</li><li>Basic analytics</li>
            </ul>
          </div>
        </label>

        <label className={`plan-card ${data.plan === "paid" ? "plan-card--selected" : ""}`}>
          <input type="radio" name="plan" value="paid" checked={data.plan === "paid"} onChange={() => setData("plan", "paid")} />
          <div className="plan-card__body">
            <span className="plan-card__name">Pro</span>
            <span className="plan-card__price">$29 / month</span>
            <ul className="plan-card__features">
              <li>Unlimited projects</li><li>Priority support</li><li>Advanced analytics</li><li>Custom branding</li>
            </ul>
          </div>
        </label>
      </div>

      {errors.plan && <span className="field-error">{errors.plan}</span>}
      {data.plan === "free" && <p className="plan-note">ℹ️ Free plan — payment and billing steps will be skipped.</p>}
    </div>
  );
}
