// apps/react-demos/demo-react-wizard/src/PersonalInfoStep.tsx
import { usePathContext } from "@daltonr/pathwrite-react";
import type { OnboardingData } from "./onboarding";

export function PersonalInfoStep() {
  const { snapshot, setData } = usePathContext<OnboardingData>();
  const data   = snapshot?.data ?? {} as OnboardingData;
  const errors = snapshot?.hasAttemptedNext ? (snapshot.fieldMessages ?? {}) : {};

  return (
    <div className="form-body">
      <p className="step-intro">Let's start with the basics — we just need a name and email.</p>

      <div className="row">
        <div className={`field ${errors.firstName ? "field--error" : ""}`}>
          <label htmlFor="firstName">First Name <span className="required">*</span></label>
          <input id="firstName" type="text" value={data.firstName ?? ""} autoFocus
            onChange={e => setData("firstName", e.target.value.trim())}
            placeholder="Jane" autoComplete="given-name" />
          {errors.firstName && <span className="field-error">{errors.firstName}</span>}
        </div>

        <div className={`field ${errors.lastName ? "field--error" : ""}`}>
          <label htmlFor="lastName">Last Name <span className="required">*</span></label>
          <input id="lastName" type="text" value={data.lastName ?? ""}
            onChange={e => setData("lastName", e.target.value.trim())}
            placeholder="Smith" autoComplete="family-name" />
          {errors.lastName && <span className="field-error">{errors.lastName}</span>}
        </div>
      </div>

      <div className={`field ${errors.email ? "field--error" : ""}`}>
        <label htmlFor="email">Email Address <span className="required">*</span></label>
        <input id="email" type="email" value={data.email ?? ""}
          onChange={e => setData("email", e.target.value.trim())}
          placeholder="jane@example.com" autoComplete="email" />
        {errors.email && <span className="field-error">{errors.email}</span>}
      </div>
    </div>
  );
}

// apps/vue-demos/demo-vue-wizard/src/PersonalInfoStep.vue
<script setup lang="ts">
import { computed } from "vue";
import { usePathContext } from "@daltonr/pathwrite-vue";
import type { OnboardingData } from "./onboarding";

const { snapshot, setData } = usePathContext<OnboardingData>();
const errors = computed(() =>
  snapshot.value?.hasAttemptedNext ? (snapshot.value.fieldMessages ?? {}) : {}
);
</script>

<template>
  <div v-if="snapshot" class="form-body">
    <p class="step-intro">Let's start with the basics — we just need a name and email.</p>

    <div class="row">
      <div class="field" :class="{ 'field--error': errors.firstName }">
        <label for="firstName">First Name <span class="required">*</span></label>
        <input id="firstName" type="text" :value="snapshot.data['firstName']" autofocus
          @input="setData('firstName', ($event.target as HTMLInputElement).value.trim())"
          placeholder="Jane" autocomplete="given-name" />
        <span v-if="errors.firstName" class="field-error">{{ errors.firstName }}</span>
      </div>
      <div class="field" :class="{ 'field--error': errors.lastName }">
        <label for="lastName">Last Name <span class="required">*</span></label>
        <input id="lastName" type="text" :value="snapshot.data['lastName']"
          @input="setData('lastName', ($event.target as HTMLInputElement).value.trim())"
          placeholder="Smith" autocomplete="family-name" />
        <span v-if="errors.lastName" class="field-error">{{ errors.lastName }}</span>
      </div>
    </div>

    <div class="field" :class="{ 'field--error': errors.email }">
      <label for="email">Email Address <span class="required">*</span></label>
      <input id="email" type="email" :value="snapshot.data['email']"
        @input="setData('email', ($event.target as HTMLInputElement).value.trim())"
        placeholder="jane@example.com" autocomplete="email" />
      <span v-if="errors.email" class="field-error">{{ errors.email }}</span>
    </div>
  </div>
</template>
