// apps/react-demos/demo-react-wizard/src/PreferencesStep.tsx
import { usePathContext } from "@daltonr/pathwrite-react";
import type { OnboardingData } from "./onboarding";

const THEME_OPTIONS = [
  { value: "light",  label: "Light",         desc: "Always bright" },
  { value: "dark",   label: "Dark",           desc: "Easy on the eyes" },
  { value: "system", label: "System Default", desc: "Follows your OS setting" },
];

export function PreferencesStep() {
  const { snapshot, setData } = usePathContext<OnboardingData>();
  const data = snapshot?.data ?? {} as OnboardingData;
  const theme         = (data.theme         as string)  ?? "system";
  const notifications = (data.notifications as boolean) ?? true;

  return (
    <div className="form-body">
      <p className="step-intro">All preferences can be changed later in your account settings.</p>

      {/* Theme */}
      <div className="pref-section">
        <p className="pref-label">Interface Theme</p>
        <div className="radio-group">
          {THEME_OPTIONS.map(opt => (
            <label key={opt.value} className="radio-option">
              <input type="radio" name="theme" value={opt.value}
                checked={theme === opt.value}
                onChange={() => setData("theme", opt.value)} />
              <span className="radio-option-label">{opt.label}</span>
              <span className="radio-option-desc">{opt.desc}</span>
            </label>
          ))}
        </div>
      </div>

      {/* Notifications */}
      <div className="pref-section">
        <p className="pref-label">Notifications</p>
        <div className="toggle-option">
          <div className="toggle-text">
            <strong>Email Notifications</strong>
            <span>Receive updates, tips, and product announcements</span>
          </div>
          <label className="toggle">
            <input type="checkbox" checked={notifications}
              onChange={e => setData("notifications", e.target.checked)} />
            <span className="toggle-track" />
            <span className="toggle-thumb" />
          </label>
        </div>
      </div>
    </div>
  );
}

// apps/vue-demos/demo-vue-wizard/src/PreferencesStep.vue
<script setup lang="ts">
import { usePathContext } from "@daltonr/pathwrite-vue";
import type { OnboardingData } from "./onboarding";

const { snapshot, setData } = usePathContext<OnboardingData>();

const THEME_OPTIONS = [
  { value: "light",  label: "Light",         desc: "Always bright" },
  { value: "dark",   label: "Dark",           desc: "Easy on the eyes" },
  { value: "system", label: "System Default", desc: "Follows your OS setting" },
];
</script>

<template>
  <div v-if="snapshot" class="form-body">
    <p class="step-intro">All preferences can be changed later in your account settings.</p>

    <div class="pref-section">
      <p class="pref-label">Interface Theme</p>
      <div class="radio-group">
        <label v-for="opt in THEME_OPTIONS" :key="opt.value" class="radio-option">
          <input type="radio" name="theme" :value="opt.value"
            :checked="snapshot.data.theme === opt.value"
            @change="setData('theme', opt.value)" />
          <span class="radio-option-label">{{ opt.label }}</span>
          <span class="radio-option-desc">{{ opt.desc }}</span>
        </label>
      </div>
    </div>

    <div class="pref-section">
      <p class="pref-label">Notifications</p>
      <div class="toggle-option">
        <div class="toggle-text">
          <strong>Email Notifications</strong>
          <span>Receive updates, tips, and product announcements</span>
        </div>
        <label class="toggle">
          <input type="checkbox" :checked="snapshot.data.notifications"
            @change="setData('notifications', ($event.target as HTMLInputElement).checked)" />
          <span class="toggle-track"></span>
          <span class="toggle-thumb"></span>
        </label>
      </div>
    </div>
  </div>
</template>
