// apps/solid-demos/demo-solid-subwizard/src/ViewDocumentStep.tsx
import { Show } from "solid-js";
import { usePathContext } from "@daltonr/pathwrite-solid";
import type { ApprovalData } from "./types";

export default function ViewDocumentStep() {
  const ctx = usePathContext<ApprovalData>();

  return (
    <Show when={ctx.snapshot()}>
      <div class="form-body">
        <p class="step-intro">
          Reviewing as <strong>{ctx.snapshot()?.data.approverName as string}</strong>. Please read the
          document carefully before making your decision.
        </p>

        <div style="background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 8px; padding: 20px 20px 16px;">
          <p style="margin: 0 0 4px; font-size: 12px; color: #9ca3af; text-transform: uppercase; letter-spacing: 0.05em;">
            Document
          </p>
          <p style="margin: 0 0 10px; font-size: 17px; font-weight: 600; color: #1f2937;">
            {ctx.snapshot()?.data.documentTitle as string}
          </p>
          <p style="margin: 0; font-size: 14px; color: #374151; white-space: pre-wrap;">
            {ctx.snapshot()?.data.documentDescription as string}
          </p>
        </div>

        <p style="font-size: 14px; color: #6b7280; margin: 0;">
          Click <strong>Next</strong> to record your decision, or <strong>Previous</strong> to return to the
          approvals list.
        </p>
      </div>
    </Show>
  );
}

// apps/angular-demos/demo-angular-subwizard/src/app/steps/view-document-step.component.ts
import { Component } from "@angular/core";
import { usePathContext } from "@daltonr/pathwrite-angular";
import type { ApprovalData } from "../approval.types";

@Component({
  selector: "app-view-document-step",
  standalone: true,
  styles: [`
    .form-body { display: flex; flex-direction: column; gap: 18px; }
    .step-intro { margin: 0; font-size: 14px; color: #5b677a; }
    .step-note  { margin: 0; font-size: 13px; color: #9ca3af; font-style: italic; }
    .document-preview { background: #f8fafc; border: 1px solid #dbe4f0; border-left: 4px solid #2563eb; border-radius: 6px; padding: 16px 20px; }
    .document-preview__label { margin: 0 0 6px; font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.06em; color: #2563eb; }
    .document-preview__title { margin: 0 0 8px; font-size: 16px; font-weight: 600; color: #1f2937; }
    .document-preview__body  { margin: 0; font-size: 14px; color: #374151; line-height: 1.6; }
  `],
  template: `
    <div class="form-body">
      <p class="step-intro">Reviewing as <strong>{{ data.approverName }}</strong>. Please read the document carefully before making your decision.</p>

      <div class="document-preview">
        <p class="document-preview__label">Document</p>
        <p class="document-preview__title">{{ data.documentTitle }}</p>
        <p class="document-preview__body">{{ data.documentDescription }}</p>
      </div>

      <p class="step-note">Click <strong>Next</strong> to record your decision, or <strong>Previous</strong> to return to the approvals list.</p>
    </div>
  `
})
export class ViewDocumentStepComponent {
  protected readonly path = usePathContext<ApprovalData>();
  protected get data(): ApprovalData { return this.path.snapshot()!.data; }
}
