// apps/react-demos/demo-react-nested/src/tabs/PersonalTab.tsx
import { usePathContext } from "@daltonr/pathwrite-react";
import type { EmployeeDetails } from "../employee-details";
import { TabBar } from "./TabBar";

export function PersonalTab() {
  const { snapshot, setData } = usePathContext<EmployeeDetails>();
  const data = snapshot.data;
  const showErrors = snapshot.hasAttemptedNext || snapshot.hasValidated;
  const errors = showErrors ? snapshot.fieldErrors : {};

  return (
    <div className="tab-content">
      <TabBar />
      <div className="form-body">
        <div className="row">
          <div className={`field ${errors.firstName ? "field--error" : ""}`}>
            <label htmlFor="firstName">First Name <span className="required">*</span></label>
            <input
              id="firstName" type="text"
              value={data.firstName ?? ""}
              onChange={e => setData("firstName", e.target.value)}
              placeholder="Jane"
              autoComplete="given-name"
            />
            {errors.firstName && <span className="field-error">{errors.firstName}</span>}
          </div>
          <div className={`field ${errors.lastName ? "field--error" : ""}`}>
            <label htmlFor="lastName">Last Name <span className="required">*</span></label>
            <input
              id="lastName" type="text"
              value={data.lastName ?? ""}
              onChange={e => setData("lastName", e.target.value)}
              placeholder="Smith"
              autoComplete="family-name"
            />
            {errors.lastName && <span className="field-error">{errors.lastName}</span>}
          </div>
        </div>

        <div className="field">
          <label htmlFor="dateOfBirth">Date of Birth <span className="optional">(optional)</span></label>
          <input
            id="dateOfBirth" type="date"
            value={data.dateOfBirth ?? ""}
            onChange={e => setData("dateOfBirth", e.target.value)}
          />
        </div>

        <div className="field">
          <label htmlFor="phone">Phone Number <span className="optional">(optional)</span></label>
          <input
            id="phone" type="tel"
            value={data.phone ?? ""}
            onChange={e => setData("phone", e.target.value)}
            placeholder="+353 86 123 4567"
            autoComplete="tel"
          />
        </div>

        <div className="field">
          <label htmlFor="personalEmail">Personal Email <span className="optional">(optional)</span></label>
          <input
            id="personalEmail" type="email"
            value={data.personalEmail ?? ""}
            onChange={e => setData("personalEmail", e.target.value)}
            placeholder="jane@personal.com"
            autoComplete="email"
          />
        </div>
      </div>
    </div>
  );
}

// apps/vue-demos/demo-vue-nested/src/tabs/PersonalTab.vue
<script setup lang="ts">
import { computed } from "vue";
import { usePathContext } from "@daltonr/pathwrite-vue";
import type { EmployeeDetails } from "../employee-details";
import TabBar from "./TabBar.vue";

const { snapshot, setData } = usePathContext<EmployeeDetails>();

const showErrors = computed(() => snapshot.value.hasAttemptedNext || snapshot.value.hasValidated);
const errors = computed(() => (showErrors.value ? snapshot.value.fieldErrors : {}));
</script>

<template>
  <div class="tab-content">
    <TabBar />
    <div class="form-body">
      <div class="row">
        <div class="field" :class="{ 'field--error': errors.firstName }">
          <label for="firstName">First Name <span class="required">*</span></label>
          <input
            id="firstName"
            type="text"
            :value="snapshot.data.firstName ?? ''"
            @input="setData('firstName', ($event.target as HTMLInputElement).value)"
            placeholder="Jane"
            autocomplete="given-name"
          />
          <span v-if="errors.firstName" class="field-error">{{ errors.firstName }}</span>
        </div>
        <div class="field" :class="{ 'field--error': errors.lastName }">
          <label for="lastName">Last Name <span class="required">*</span></label>
          <input
            id="lastName"
            type="text"
            :value="snapshot.data.lastName ?? ''"
            @input="setData('lastName', ($event.target as HTMLInputElement).value)"
            placeholder="Smith"
            autocomplete="family-name"
          />
          <span v-if="errors.lastName" class="field-error">{{ errors.lastName }}</span>
        </div>
      </div>

      <div class="field">
        <label for="dateOfBirth">Date of Birth <span class="optional">(optional)</span></label>
        <input
          id="dateOfBirth"
          type="date"
          :value="snapshot.data.dateOfBirth ?? ''"
          @input="setData('dateOfBirth', ($event.target as HTMLInputElement).value)"
        />
      </div>

      <div class="field">
        <label for="phone">Phone Number <span class="optional">(optional)</span></label>
        <input
          id="phone"
          type="tel"
          :value="snapshot.data.phone ?? ''"
          @input="setData('phone', ($event.target as HTMLInputElement).value)"
          placeholder="+353 86 123 4567"
          autocomplete="tel"
        />
      </div>

      <div class="field">
        <label for="personalEmail">Personal Email <span class="optional">(optional)</span></label>
        <input
          id="personalEmail"
          type="email"
          :value="snapshot.data.personalEmail ?? ''"
          @input="setData('personalEmail', ($event.target as HTMLInputElement).value)"
          placeholder="jane@personal.com"
          autocomplete="email"
        />
      </div>
    </div>
  </div>
</template>
