// apps/svelte-demos/demo-svelte-stepchoice/src/USAddressForm.svelte
<script lang="ts">
  import { usePathContext } from "@daltonr/pathwrite-svelte";
  import { US_STATES, type AddressData } from "./address-path";

  const ctx = usePathContext<AddressData>();
  let errors = $derived(ctx.snapshot?.hasAttemptedNext ? ctx.snapshot.fieldErrors : {});
</script>

{#if ctx.snapshot}
  <div class="form-body">
    <div class="field" class:field--error={errors.streetAddress}>
      <label for="streetAddress">Street Address <span class="required">*</span></label>
      <input
        id="streetAddress"
        type="text"
        value={ctx.snapshot.data.streetAddress ?? ""}
        oninput={(e) => ctx.setData("streetAddress", e.currentTarget.value)}
        placeholder="123 Main St"
        autocomplete="address-line1"
        autofocus
      />
      {#if errors.streetAddress}<span class="field-error">{errors.streetAddress}</span>{/if}
    </div>

    <div class="field">
      <label for="aptUnit">Apt / Unit <span class="optional">(optional)</span></label>
      <input
        id="aptUnit"
        type="text"
        value={ctx.snapshot.data.aptUnit ?? ""}
        oninput={(e) => ctx.setData("aptUnit", e.currentTarget.value)}
        placeholder="Apt 4B"
        autocomplete="address-line2"
      />
    </div>

    <div class="row">
      <div class="field" class:field--error={errors.city}>
        <label for="city">City <span class="required">*</span></label>
        <input
          id="city"
          type="text"
          value={ctx.snapshot.data.city ?? ""}
          oninput={(e) => ctx.setData("city", e.currentTarget.value)}
          placeholder="New York"
          autocomplete="address-level2"
        />
        {#if errors.city}<span class="field-error">{errors.city}</span>{/if}
      </div>

      <div class="field" class:field--error={errors.state}>
        <label for="state">State <span class="required">*</span></label>
        <select
          id="state"
          value={ctx.snapshot.data.state ?? ""}
          onchange={(e) => ctx.setData("state", e.currentTarget.value)}
          autocomplete="address-level1"
        >
          <option value="">Select state…</option>
          {#each US_STATES as s}
            <option value={s.code}>{s.name}</option>
          {/each}
        </select>
        {#if errors.state}<span class="field-error">{errors.state}</span>{/if}
      </div>
    </div>

    <div class="field field--short" class:field--error={errors.zipCode}>
      <label for="zipCode">ZIP Code <span class="required">*</span></label>
      <input
        id="zipCode"
        type="text"
        value={ctx.snapshot.data.zipCode ?? ""}
        oninput={(e) => ctx.setData("zipCode", e.currentTarget.value)}
        placeholder="90210"
        autocomplete="postal-code"
        maxlength="10"
      />
      {#if errors.zipCode}<span class="field-error">{errors.zipCode}</span>{/if}
    </div>
  </div>
{/if}

// apps/react-demos/demo-react-stepchoice/src/USAddressForm.tsx
import { usePathContext } from "@daltonr/pathwrite-react";
import { US_STATES, type AddressData } from "./address-path";

export function USAddressForm() {
  const { snapshot, setData } = usePathContext<AddressData>();
  const snap   = snapshot!;
  const data   = snap.data;
  const errors = snap.hasAttemptedNext ? snap.fieldErrors : {};

  return (
    <div className="form-body">
      <div className={`field ${errors.streetAddress ? "field--error" : ""}`}>
        <label htmlFor="streetAddress">Street Address <span className="required">*</span></label>
        <input
          id="streetAddress"
          type="text"
          value={data.streetAddress ?? ""}
          onChange={e => setData("streetAddress", e.target.value)}
          placeholder="123 Main Street"
          autoComplete="address-line1"
          autoFocus
        />
        {errors.streetAddress && <span className="field-error">{errors.streetAddress}</span>}
      </div>

      <div className="field">
        <label htmlFor="aptUnit">Apt / Unit <span className="optional">(optional)</span></label>
        <input
          id="aptUnit"
          type="text"
          value={data.aptUnit ?? ""}
          onChange={e => setData("aptUnit", e.target.value)}
          placeholder="Apt 4B"
          autoComplete="address-line2"
        />
      </div>

      <div className="row">
        <div className={`field ${errors.city ? "field--error" : ""}`}>
          <label htmlFor="city">City <span className="required">*</span></label>
          <input
            id="city"
            type="text"
            value={data.city ?? ""}
            onChange={e => setData("city", e.target.value)}
            placeholder="Springfield"
            autoComplete="address-level2"
          />
          {errors.city && <span className="field-error">{errors.city}</span>}
        </div>

        <div className={`field ${errors.state ? "field--error" : ""}`}>
          <label htmlFor="state">State <span className="required">*</span></label>
          <select
            id="state"
            value={data.state ?? ""}
            onChange={e => setData("state", e.target.value)}
            autoComplete="address-level1"
          >
            <option value="">Select state…</option>
            {US_STATES.map(s => (
              <option key={s.code} value={s.code}>{s.name}</option>
            ))}
          </select>
          {errors.state && <span className="field-error">{errors.state}</span>}
        </div>
      </div>

      <div className="field field--short">
        <label htmlFor="zipCode">ZIP Code <span className="required">*</span></label>
        <input
          id="zipCode"
          type="text"
          value={data.zipCode ?? ""}
          onChange={e => setData("zipCode", e.target.value)}
          placeholder="90210"
          autoComplete="postal-code"
          maxLength={10}
        />
        {errors.zipCode && <span className="field-error">{errors.zipCode}</span>}
      </div>
    </div>
  );
}
