// packages/angular-adapter/src/index.ts
import { Injectable, OnDestroy, DestroyRef, signal, Signal, inject } from "@angular/core";
import { BehaviorSubject, Observable, Subject } from "rxjs";
import {
  PathData,
  PathDefinition,
  PathEngine,
  PathEvent,
  PathSnapshot
} from "@daltonr/pathwrite-core";

/**
 * Angular facade over PathEngine. Provide at component level for an isolated
 * instance per component; Angular handles cleanup via ngOnDestroy.
 *
 * The optional generic `TData` narrows `state$`, `stateSignal`, `snapshot()`,
 * and `setData()` to your data shape. It is a **type-level assertion** — no
 * runtime validation is performed. Inject as `PathFacade` (untyped default)
 * then cast:
 *
 * ```typescript
 * const facade = inject(PathFacade) as PathFacade<MyData>;
 * facade.snapshot()?.data.name; // typed as string (or whatever MyData defines)
 * ```
 */
@Injectable()
export class PathFacade<TData extends PathData = PathData> implements OnDestroy {
  private _engine = new PathEngine();
  private readonly _state$ = new BehaviorSubject<PathSnapshot<TData> | null>(null);
  private readonly _events$ = new Subject<PathEvent>();
  private _unsubscribeFromEngine: () => void = () => {};
  private readonly _stateSignal = signal<PathSnapshot<TData> | null>(null);

  public readonly state$: Observable<PathSnapshot<TData> | null> = this._state$.asObservable();
  public readonly events$: Observable<PathEvent> = this._events$.asObservable();
  /** Signal version of state$. Updates on every path state change. Requires Angular 16+. */
  public readonly stateSignal: Signal<PathSnapshot<TData> | null> = this._stateSignal.asReadonly();

  public constructor() {
    this.connectEngine(this._engine);
  }

  /**
   * Adopt an externally-managed `PathEngine` — for example, the engine returned
   * by `restoreOrStart()` from `@daltonr/pathwrite-store`.
   *
   * The facade immediately reflects the engine's current state and forwards all
   * subsequent events. The **caller** is responsible for the engine's lifecycle
   * (starting, cleanup); the facade only subscribes to it.
   *
   * ```typescript
   * const { engine } = await restoreOrStart({ store, key, path, initialData, observers: [...] });
   * facade.adoptEngine(engine);
   * ```
   */
  public adoptEngine(engine: PathEngine): void {
    // Disconnect from whatever engine we're currently listening to
    this._unsubscribeFromEngine();
    this._engine = engine;
    this.connectEngine(engine);
  }

  private connectEngine(engine: PathEngine): void {
    // Seed state immediately — critical when restoring a persisted path since
    // the engine is already running before the facade connects to it.
    const current = engine.snapshot() as PathSnapshot<TData> | null;
    this._state$.next(current);
    this._stateSignal.set(current);

    this._unsubscribeFromEngine = engine.subscribe((event) => {
      this._events$.next(event);
      if (event.type === "stateChanged" || event.type === "resumed") {
        this._state$.next(event.snapshot as PathSnapshot<TData>);
        this._stateSignal.set(event.snapshot as PathSnapshot<TData>);
      } else if (event.type === "completed" || event.type === "cancelled") {
        this._state$.next(null);
        this._stateSignal.set(null);
      }
    });
  }

  public ngOnDestroy(): void {
    this._unsubscribeFromEngine();
    this._events$.complete();
    this._state$.complete();
  }

  public start(path: PathDefinition<any>, initialData: PathData = {}): Promise<void> {
    return this._engine.start(path, initialData);
  }

  /**
   * Tears down any active path (without firing lifecycle hooks) and immediately
   * starts the given path fresh. Safe to call whether or not a path is running.
   * Use for "Start over" / retry flows without destroying and re-creating the
   * component that provides this facade.
   */
  public restart(): Promise<void> {
    return this._engine.restart();
  }

  /** Re-runs the operation that set `snapshot().error`. Increments `retryCount` on repeated failure. No-op when there is no pending error. */
  public retry(): Promise<void> {
    return this._engine.retry();
  }

  /** Pauses the path with intent to return. Emits `suspended`. All state is preserved. */
  public suspend(): Promise<void> {
    return this._engine.suspend();
  }

  public startSubPath(path: PathDefinition<any>, initialData: PathData = {}, meta?: Record<string, unknown>): Promise<void> {
    return this._engine.startSubPath(path, initialData, meta);
  }

  public next(): Promise<void> {
    return this._engine.next();
  }

  public previous(): Promise<void> {
    return this._engine.previous();
  }

  public cancel(): Promise<void> {
    return this._engine.cancel();
  }

  public setData<K extends string & keyof TData>(key: K, value: TData[K]): Promise<void> {
    return this._engine.setData(key, value as unknown);
  }

  /** Reset the current step's data to what it was when the step was entered.
   *  Useful for "Clear" or "Reset" buttons that undo changes within a step. */
  public resetStep(): Promise<void> {
    return this._engine.resetStep();
  }

  public goToStep(stepId: string): Promise<void> {
    return this._engine.goToStep(stepId);
  }

  /** Jump to a step by ID, checking the current step's canMoveNext (forward) or
   *  canMovePrevious (backward) guard first. Navigation is blocked if the guard
   *  returns false. Throws if the step ID does not exist. */
  public goToStepChecked(stepId: string): Promise<void> {
    return this._engine.goToStepChecked(stepId);
  }

  public validate(): void {
    this._engine.validate();
  }

  public snapshot(): PathSnapshot<TData> | null {
    return this._state$.getValue();
  }
}

// ---------------------------------------------------------------------------
// usePathContext() - Signal-based path access
// ---------------------------------------------------------------------------

/**
 * Return type of `usePathContext()`. Provides signal-based reactive access to the
 * path state and strongly-typed navigation actions. Mirrors React's `usePathContext()`
 * return type for consistency across adapters.
 */
export interface UsePathContextReturn<TData extends PathData = PathData> {
  /** Current path snapshot as a signal. Returns `null` when no path is active. */
  snapshot: Signal<PathSnapshot<TData> | null>;
  /** Start (or restart) a path. */
  start: (path: PathDefinition<any>, initialData?: PathData) => Promise<void>;
  /** Push a sub-path onto the stack. */
  startSubPath: (path: PathDefinition<any>, initialData?: PathData, meta?: Record<string, unknown>) => Promise<void>;
  /** Advance one step. Completes the path on the last step. */
  next: () => Promise<void>;
  /** Go back one step. No-op when already on the first step. */
  previous: () => Promise<void>;
  /** Cancel the active path (or sub-path). */
  cancel: () => Promise<void>;
  /** Update a single data field. */
  setData: <K extends string & keyof TData>(key: K, value: TData[K]) => Promise<void>;
  /** Reset the current step's data to what it was when the step was entered. */
  resetStep: () => Promise<void>;
  /** Jump to a step by ID without checking guards. */
  goToStep: (stepId: string) => Promise<void>;
  /** Jump to a step by ID, checking guards first. */
  goToStepChecked: (stepId: string) => Promise<void>;
  /**
   * Tears down any active path and immediately starts the given path fresh.
   * Use for "Start over" / retry flows.
   */
  restart: () => Promise<void>;
  /** Re-run the operation that set `snapshot().error`. */
  retry: () => Promise<void>;
  /** Pause with intent to return, preserving all state. Emits `suspended`. */
  suspend: () => Promise<void>;
}

/**
 * Access the nearest `PathFacade`'s path instance for use in Angular step components.
 * Requires `PathFacade` to be provided in the component's injector tree (either via
 * `providers: [PathFacade]` in the component or a parent component).
 *
 * **This is the recommended way to consume Pathwrite in Angular components** — it
 * provides the same ergonomic API as React's `usePathContext()` and Vue's `usePathContext()`.
 * No template references or manual facade injection needed.
 *
 * The optional generic `TData` narrows `snapshot().data` and `setData()` to your
 * data shape. It is a **type-level assertion**, not a runtime guarantee.
 *
 * @example
 * ```typescript
 * @Component({
 *   selector: 'app-contact-step',
 *   standalone: true,
 *   providers: [PathFacade],  // ← Provide at this component or a parent
 *   template: `
 *     @if (path.snapshot(); as s) {
 *       <div>Step: {{ s.activeStep?.title }}</div>
 *       <button (click)="path.next()">Next</button>
 *     }
 *   `
 * })
 * export class ContactStepComponent {
 *   protected readonly path = usePathContext<ContactData>();
 *
 *   updateName(name: string) {
 *     this.path.setData('name', name);
 *   }
 * }
 * ```
 *
 * @throws Error if PathFacade is not provided in the injector tree
 */
export function usePathContext<TData extends PathData = PathData>(): UsePathContextReturn<TData> {
  const facade = inject(PathFacade, { optional: true }) as PathFacade<TData> | null;

  if (!facade) {
    throw new Error(
      "usePathContext() requires PathFacade to be provided. " +
      "Add 'providers: [PathFacade]' to your component or a parent component."
    );
  }

  return {
    snapshot: facade.stateSignal,
    start: (path, initialData = {}) => facade.start(path, initialData),
    startSubPath: (path, initialData = {}, meta) => facade.startSubPath(path, initialData, meta),
    next: () => facade.next(),
    previous: () => facade.previous(),
    cancel: () => facade.cancel(),
    setData: (key, value) => facade.setData(key, value),
    resetStep: () => facade.resetStep(),
    goToStep: (stepId) => facade.goToStep(stepId),
    goToStepChecked: (stepId) => facade.goToStepChecked(stepId),
    restart: () => facade.restart(),
    retry: () => facade.retry(),
    suspend: () => facade.suspend(),
  };
}

// ---------------------------------------------------------------------------
// Forms integration
// ---------------------------------------------------------------------------

/**
 * Minimal interface describing what syncFormGroup needs from an Angular
 * FormGroup. Typed as a duck interface so that @angular/forms is not a
 * required import — any object with getRawValue() and valueChanges works.
 *
 * Angular's FormGroup satisfies this interface automatically.
 */
export interface FormGroupLike {
  /** Returns all control values including disabled ones (FormGroup.getRawValue()). */
  getRawValue(): Record<string, unknown>;
  /** Observable that emits whenever any control value changes. */
  readonly valueChanges: Observable<unknown>;
}

/**
 * Syncs every key of an Angular FormGroup to the path engine via setData.
 *
 * - Immediately writes getRawValue() to the facade so canMoveNext guards
 *   evaluate against the current form state on the very first snapshot.
 * - Subscribes to valueChanges and re-applies getRawValue() on every emission
 *   so disabled controls are always included.
 * - Guards against calling setData when no path is active, so it is safe to
 *   call syncFormGroup before or after facade.start().
 * - Returns a cleanup function that unsubscribes from the observable.
 *   Pass a DestroyRef to wire cleanup automatically to the component lifecycle.
 *
 * @example
 * ```typescript
 * export class MyStepComponent implements OnInit {
 *   private readonly facade = inject(PathFacade) as PathFacade<MyData>;
 *   protected readonly form = new FormGroup({
 *     name:  new FormControl('', Validators.required),
 *     email: new FormControl(''),
 *   });
 *
 *   ngOnInit() {
 *     syncFormGroup(this.facade, this.form, inject(DestroyRef));
 *   }
 * }
 * ```
 */
export function syncFormGroup<TData extends PathData = PathData>(
  facade: PathFacade<TData>,
  formGroup: FormGroupLike,
  destroyRef?: DestroyRef
): () => void {
  const baseFacade = facade as PathFacade<PathData>;

  function applyValues(): void {
    if (baseFacade.snapshot() === null) return; // no active path — nothing to sync
    for (const [key, value] of Object.entries(formGroup.getRawValue())) {
      void baseFacade.setData(key, value);
    }
  }

  // Write current form values immediately so guards see the initial state.
  applyValues();

  const subscription = formGroup.valueChanges.subscribe(() => applyValues());

  const cleanup = () => subscription.unsubscribe();
  destroyRef?.onDestroy(cleanup);
  return cleanup;
}

// Re-export core types for convenience (users don't need to import from @daltonr/pathwrite-core)
export type {
  PathData,
  FieldErrors,
  PathDefinition,
  PathEvent,
  PathSnapshot,
  PathStep,
  PathStepContext,
  ProgressLayout,
  RootProgress,
  SerializedPathState
} from "@daltonr/pathwrite-core";

export { PathEngine } from "@daltonr/pathwrite-core";

// packages/solid-adapter/src/index.tsx
import {
  createSignal,
  onCleanup,
  onMount,
  createContext,
  useContext,
  createEffect,
  For,
  Show,
  type Component,
  type JSX,
  type Accessor,
} from "solid-js";
import {
  PathData,
  PathDefinition,
  PathEngine,
  PathEvent,
  PathSnapshot,
  ProgressLayout,
  RootProgress,
  formatFieldKey,
  errorPhaseMessage,
} from "@daltonr/pathwrite-core";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface UsePathOptions {
  /**
   * An externally-managed `PathEngine` to subscribe to — for example, the engine
   * returned by `createPersistedEngine()` from `@daltonr/pathwrite-store`.
   *
   * When provided:
   * - `usePath` will **not** create its own engine.
   * - The snapshot is seeded immediately from the engine's current state.
   * - The engine lifecycle (start / cleanup) is the **caller's responsibility**.
   * - `PathShell` will skip its own `autoStart` call.
   */
  engine?: PathEngine;
  /** Called for every engine event (stateChanged, completed, cancelled, resumed). */
  onEvent?: (event: PathEvent) => void;
}

export interface UsePathReturn<TData extends PathData = PathData> {
  /**
   * Reactive snapshot accessor. Call `snapshot()` to read the current value.
   * Automatically tracked as a reactive dependency when read inside JSX or effects.
   */
  snapshot: Accessor<PathSnapshot<TData> | null>;
  /** Start (or restart) a path. */
  start: (path: PathDefinition<any>, initialData?: PathData) => Promise<void>;
  /** Push a sub-path onto the stack. Requires an active path. Pass an optional `meta` object for correlation — it is returned unchanged to the parent step's `onSubPathComplete` / `onSubPathCancel` hooks. */
  startSubPath: (path: PathDefinition<any>, initialData?: PathData, meta?: Record<string, unknown>) => Promise<void>;
  /** Advance one step. Completes the path on the last step. */
  next: () => Promise<void>;
  /** Go back one step. No-op when already on the first step of a top-level path. Pops back to the parent path when on the first step of a sub-path. */
  previous: () => Promise<void>;
  /** Cancel the active path (or sub-path). */
  cancel: () => Promise<void>;
  /** Jump directly to a step by ID. Calls onLeave / onEnter but bypasses guards and shouldSkip. */
  goToStep: (stepId: string) => Promise<void>;
  /** Jump directly to a step by ID, checking the current step's canMoveNext (forward) or canMovePrevious (backward) guard first. Navigation is blocked if the guard returns false. */
  goToStepChecked: (stepId: string) => Promise<void>;
  /** Update a single data value; triggers re-renders via stateChanged. When `TData` is specified, `key` and `value` are type-checked against your data shape. */
  setData: <K extends string & keyof TData>(key: K, value: TData[K]) => Promise<void>;
  /** Reset the current step's data to what it was when the step was entered. Useful for "Clear" or "Reset" buttons. */
  resetStep: () => Promise<void>;
  /**
   * Tear down any active path (without firing hooks) and immediately start the
   * given path fresh. Safe to call whether or not a path is currently active.
   * Use for "Start over" / retry flows without remounting the component.
   */
  restart: () => Promise<void>;
  /** Re-runs the operation that set `snapshot().error`. Increments `retryCount` on repeated failure. No-op when there is no pending error. */
  retry: () => Promise<void>;
  /** Pauses the path with intent to return. Emits `suspended`. All state is preserved. */
  suspend: () => Promise<void>;
  /** Trigger inline validation on all steps without navigating. Sets `snapshot().hasValidated`. */
  validate: () => void;
}

// ---------------------------------------------------------------------------
// usePath composable
// ---------------------------------------------------------------------------

export function usePath<TData extends PathData = PathData>(options?: UsePathOptions): UsePathReturn<TData> {
  const engine = options?.engine ?? new PathEngine();

  const [snapshot, setSnapshot] = createSignal<PathSnapshot<TData> | null>(
    engine.snapshot() as PathSnapshot<TData> | null,
    // always notify — PathEngine produces new snapshot objects on every event
    { equals: false }
  );

  const unsubscribe = engine.subscribe((event: PathEvent) => {
    if (event.type === "stateChanged" || event.type === "resumed") {
      setSnapshot(event.snapshot as PathSnapshot<TData>);
    } else if (event.type === "completed" || event.type === "cancelled") {
      setSnapshot(engine.snapshot() as PathSnapshot<TData> | null);
    }
    options?.onEvent?.(event);
  });

  onCleanup(unsubscribe);

  const start = (path: PathDefinition<any>, initialData: PathData = {}): Promise<void> =>
    engine.start(path, initialData);

  const startSubPath = (path: PathDefinition<any>, initialData: PathData = {}, meta?: Record<string, unknown>): Promise<void> =>
    engine.startSubPath(path, initialData, meta);

  const next = (): Promise<void> => engine.next();
  const previous = (): Promise<void> => engine.previous();
  const cancel = (): Promise<void> => engine.cancel();
  const goToStep = (stepId: string): Promise<void> => engine.goToStep(stepId);
  const goToStepChecked = (stepId: string): Promise<void> => engine.goToStepChecked(stepId);

  const setData = (<K extends string & keyof TData>(key: K, value: TData[K]): Promise<void> =>
    engine.setData(key, value as unknown)) as UsePathReturn<TData>["setData"];

  const resetStep = (): Promise<void> => engine.resetStep();
  const restart = (): Promise<void> => engine.restart();
  const retry = (): Promise<void> => engine.retry();
  const suspend = (): Promise<void> => engine.suspend();
  const validate = (): void => engine.validate();

  return { snapshot, start, startSubPath, next, previous, cancel, goToStep, goToStepChecked, setData, resetStep, restart, retry, suspend, validate };
}

// ---------------------------------------------------------------------------
// Context — provide / useContext
// ---------------------------------------------------------------------------

interface PathContextValue {
  path: UsePathReturn;
  services: unknown;
}

const PathContext = createContext<PathContextValue | undefined>(undefined);

/**
 * Access the nearest `PathShell`'s path instance and optional services object.
 * Throws if used outside of a PathShell component.
 *
 * Both generics are type-level assertions, not runtime guarantees:
 * - `TData` narrows `snapshot().data`
 * - `TServices` types the `services` value — must match what was passed to `PathShell`
 */
export function usePathContext<TData extends PathData = PathData, TServices = unknown>(): Omit<UsePathReturn<TData>, "snapshot"> & { snapshot: Accessor<PathSnapshot<TData>>; services: TServices } {
  const ctx = useContext(PathContext);
  if (!ctx) {
    throw new Error("usePathContext must be used within a PathShell component.");
  }
  return {
    ...(ctx.path as unknown as Omit<UsePathReturn<TData>, "snapshot"> & { snapshot: Accessor<PathSnapshot<TData>> }),
    services: ctx.services as TServices,
  };
}

// ---------------------------------------------------------------------------
// Default UI — PathShell
// ---------------------------------------------------------------------------

export interface PathShellActions {
  next: () => Promise<void>;
  previous: () => Promise<void>;
  cancel: () => Promise<void>;
  goToStep: (stepId: string) => Promise<void>;
  goToStepChecked: (stepId: string) => Promise<void>;
  setData: (key: string, value: unknown) => Promise<void>;
  restart: () => Promise<void>;
  retry: () => Promise<void>;
  suspend: () => Promise<void>;
}

export interface PathShellProps {
  path: PathDefinition<any>;
  /**
   * An externally-managed engine — for example, the engine returned by
   * `createPersistedEngine()`. When supplied, `PathShell` will skip its own
   * `start()` call and drive the UI from the provided engine instead.
   */
  engine?: PathEngine;
  initialData?: PathData;
  autoStart?: boolean;
  /**
   * Step render functions keyed by step ID (or `formId` for StepChoice steps).
   * ```tsx
   * <PathShell steps={{ details: (snap) => <DetailsStep snapshot={snap} />, review: (snap) => <ReviewStep snapshot={snap} /> }} />
   * ```
   */
  steps?: Record<string, (snapshot: PathSnapshot) => JSX.Element>;
  onComplete?: (data: PathData) => void;
  onCancel?: (data: PathData) => void;
  onEvent?: (event: PathEvent) => void;
  renderHeader?: (snapshot: PathSnapshot) => JSX.Element;
  renderFooter?: (snapshot: PathSnapshot, actions: PathShellActions) => JSX.Element;
  backLabel?: string;
  nextLabel?: string;
  completeLabel?: string;
  loadingLabel?: string;
  cancelLabel?: string;
  hideCancel?: boolean;
  hideProgress?: boolean;
  /** If true, hide the footer (navigation buttons). The error panel is still shown on async failure regardless of this prop. */
  hideFooter?: boolean;
  /**
   * Footer layout mode:
   * - `"auto"` (default): Uses "form" for single-step top-level paths, "wizard" otherwise.
   * - `"wizard"`: Back button on left, Cancel and Submit together on right.
   * - `"form"`: Cancel on left, Submit alone on right. Back button never shown.
   */
  footerLayout?: "wizard" | "form" | "auto";
  /**
   * Controls whether the shell renders its auto-generated field-error summary box.
   * - `"summary"` (default): Shell renders the labeled error list below the step body.
   * - `"inline"`: Suppress the summary — handle errors inside the step component instead.
   * - `"both"`: Render the shell summary AND whatever the step renders.
   */
  validationDisplay?: "summary" | "inline" | "both";
  /**
   * Controls how progress bars are arranged when a sub-path is active.
   * - `"merged"` (default): Root and sub-path bars in one card.
   * - `"split"`: Root and sub-path bars as separate cards.
   * - `"rootOnly"`: Only the root bar — sub-path bar hidden.
   * - `"activeOnly"`: Only the active (sub-path) bar — root bar hidden.
   */
  progressLayout?: ProgressLayout;
  /**
   * Services object passed through context to all step components.
   * Step components access it via `usePathContext<TData, TServices>()`.
   */
  services?: object | null;
  /** When true, calls `validate()` on the engine so all steps show inline errors simultaneously. Useful when this shell is nested inside a step of an outer shell: bind to the outer snapshot's `hasAttemptedNext`. */
  validateWhen?: boolean;
  class?: string;
  /**
   * Content rendered when `snapshot.status === "completed"` (i.e. after the path
   * finishes with `completionBehaviour: "stayOnFinal"`). Defaults to a simple
   * "All done." panel with a Restart button.
   */
  completionContent?: (snapshot: PathSnapshot) => JSX.Element;
}

export const PathShell: Component<PathShellProps> = (props) => {
  const pathReturn = usePath({
    engine: props.engine,
    onEvent(event) {
      props.onEvent?.(event);
      if (event.type === "completed") props.onComplete?.(event.data as PathData);
      if (event.type === "cancelled") props.onCancel?.(event.data as PathData);
    },
  });

  const { snapshot, start, next, previous, cancel, goToStep, goToStepChecked, setData, restart, retry, suspend, validate } = pathReturn;

  onMount(() => {
    if (props.autoStart !== false && !props.engine) {
      start(props.path, props.initialData ?? {});
    }
  });

  createEffect(() => {
    if (props.validateWhen) validate();
  });

  const contextValue: PathContextValue = { path: pathReturn, services: props.services ?? null };

  const actions: PathShellActions = {
    next, previous, cancel, goToStep, goToStepChecked,
    setData: (key, value) => setData(key as any, value as any),
    restart: () => restart(),
    retry: () => retry(),
    suspend: () => suspend(),
  };

  // Convenience — non-null snapshot, only valid inside <Show when={snapshot()}>
  const snap = () => snapshot()!;

  const shellClass = () => {
    const base = "pw-shell";
    const layout = props.progressLayout;
    const mod = layout && layout !== "merged" ? ` pw-shell--progress-${layout}` : "";
    return props.class ? `${base}${mod} ${props.class}` : `${base}${mod}`;
  };

  const showRoot = () => !props.hideProgress && !!snap().rootProgress && props.progressLayout !== "activeOnly";
  const showActive = () => !props.hideProgress && (snap().stepCount > 1 || snap().nestingLevel > 0) && props.progressLayout !== "rootOnly";

  const stepContent = () => {
    const s = snap();
    const key = s.formId ?? s.stepId;
    const render = props.steps?.[key];
    return render ? render(s) : null;
  };

  const showValidation = () =>
    props.validationDisplay !== "inline" &&
    (snap().hasAttemptedNext || snap().hasValidated) &&
    Object.keys(snap().fieldErrors).length > 0;

  const showWarnings = () =>
    props.validationDisplay !== "inline" &&
    Object.keys(snap().fieldWarnings).length > 0;

  const showBlockingError = () =>
    props.validationDisplay !== "inline" &&
    (snap().hasAttemptedNext || snap().hasValidated) &&
    !!snap().blockingError;

  const resolvedFooterLayout = () => {
    const fl = props.footerLayout ?? "auto";
    if (fl !== "auto") return fl;
    return snap().stepCount === 1 && snap().nestingLevel === 0 ? "form" : "wizard";
  };

  return (
    <PathContext.Provider value={contextValue}>
      <Show
        when={snapshot()}
        fallback={
          <div class="pw-shell">
            <div class="pw-shell__empty">
              <p>No active path.</p>
              <Show when={props.autoStart === false}>
                <button
                  type="button"
                  class="pw-shell__start-btn"
                  onClick={() => start(props.path, props.initialData ?? {})}
                >
                  Start
                </button>
              </Show>
            </div>
          </div>
        }
      >
        <div class={shellClass()}>
          {/* Root progress — persistent top-level bar visible during sub-paths */}
          <Show when={showRoot()}>
            <SolidRootProgress root={snap().rootProgress!} />
          </Show>
          {/* Header — progress (active path) */}
          <Show when={showActive()}>
            {props.renderHeader
              ? props.renderHeader(snap())
              : <SolidHeader snapshot={snap()} />}
          </Show>
          {/* Completion panel — shown when path finishes with stayOnFinal */}
          <Show when={snap().status === "completed"}>
            <div class="pw-shell__body">
              {props.completionContent
                ? props.completionContent(snap())
                : (
                  <div class="pw-shell__completion">
                    <p class="pw-shell__completion-message">All done.</p>
                    <button
                      type="button"
                      class="pw-shell__completion-restart"
                      onClick={() => restart()}
                    >
                      Start over
                    </button>
                  </div>
                )
              }
            </div>
          </Show>
          {/* Body — step content (hidden when completed) */}
          <Show when={snap().status !== "completed"}>
          <div class="pw-shell__body">{stepContent()}</div>
          {/* Validation messages */}
          <Show when={showValidation()}>
            <ul class="pw-shell__validation">
              <For each={Object.entries(snap().fieldErrors)}>
                {([key, msg]) => (
                  <li class="pw-shell__validation-item">
                    <Show when={key !== "_"}>
                      <span class="pw-shell__validation-label">{formatFieldKey(key)}</span>
                    </Show>
                    {msg}
                  </li>
                )}
              </For>
            </ul>
          </Show>
          {/* Warning messages — non-blocking, shown immediately */}
          <Show when={showWarnings()}>
            <ul class="pw-shell__warnings">
              <For each={Object.entries(snap().fieldWarnings)}>
                {([key, msg]) => (
                  <li class="pw-shell__warnings-item">
                    <Show when={key !== "_"}>
                      <span class="pw-shell__warnings-label">{formatFieldKey(key)}</span>
                    </Show>
                    {msg}
                  </li>
                )}
              </For>
            </ul>
          </Show>
          {/* Blocking error */}
          <Show when={showBlockingError()}>
            <p class="pw-shell__blocking-error">{snap().blockingError}</p>
          </Show>
          {/* Error panel or footer */}
          <Show
            when={snap().status === "error" && snap().error}
            fallback={
              <Show when={!props.hideFooter}>
                {props.renderFooter
                  ? props.renderFooter(snap(), actions)
                  : <SolidFooter
                      snapshot={snap()}
                      actions={actions}
                      backLabel={props.backLabel ?? "Previous"}
                      nextLabel={props.nextLabel ?? "Next"}
                      completeLabel={props.completeLabel ?? "Complete"}
                      loadingLabel={props.loadingLabel}
                      cancelLabel={props.cancelLabel ?? "Cancel"}
                      hideCancel={props.hideCancel ?? false}
                      footerLayout={resolvedFooterLayout()}
                    />
                }
              </Show>
            }
          >
            <SolidErrorPanel snapshot={snap()} actions={actions} />
          </Show>
          </Show>{/* end status !== completed */}
        </div>
      </Show>
    </PathContext.Provider>
  );
};

// ---------------------------------------------------------------------------
// Root progress
// ---------------------------------------------------------------------------

function SolidRootProgress(props: { root: RootProgress }) {
  return (
    <div class="pw-shell__root-progress">
      <div class="pw-shell__steps">
        <For each={props.root.steps}>
          {(step, i) => (
            <div class={`pw-shell__step pw-shell__step--${step.status}`}>
              <span class="pw-shell__step-dot">
                {step.status === "completed" ? "✓" : String(i() + 1)}
              </span>
              <span class="pw-shell__step-label">{step.title ?? step.id}</span>
            </div>
          )}
        </For>
      </div>
      <div class="pw-shell__track">
        <div class="pw-shell__track-fill" style={{ width: `${props.root.progress * 100}%` }} />
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Default header (progress indicator)
// ---------------------------------------------------------------------------

function SolidHeader(props: { snapshot: PathSnapshot }) {
  return (
    <div class="pw-shell__header">
      <div class="pw-shell__steps">
        <For each={props.snapshot.steps}>
          {(step, i) => (
            <div class={`pw-shell__step pw-shell__step--${step.status}`}>
              <span class="pw-shell__step-dot">
                {step.status === "completed" ? "✓" : String(i() + 1)}
              </span>
              <span class="pw-shell__step-label">{step.title ?? step.id}</span>
            </div>
          )}
        </For>
      </div>
      <div class="pw-shell__track">
        <div class="pw-shell__track-fill" style={{ width: `${props.snapshot.progress * 100}%` }} />
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Error panel
// ---------------------------------------------------------------------------

function SolidErrorPanel(props: { snapshot: PathSnapshot; actions: PathShellActions }) {
  const error = () => props.snapshot.error!;
  const escalated = () => error().retryCount >= 2;
  const title = () => escalated() ? "Still having trouble." : "Something went wrong.";
  const phaseMsg = () => errorPhaseMessage(error().phase);

  return (
    <div class="pw-shell__error">
      <div class="pw-shell__error-title">{title()}</div>
      <div class="pw-shell__error-message">
        {phaseMsg()}{error().message ? ` ${error().message}` : ""}
      </div>
      <div class="pw-shell__error-actions">
        <Show when={!escalated()}>
          <button type="button" class="pw-shell__btn pw-shell__btn--retry" onClick={props.actions.retry}>
            Try again
          </button>
        </Show>
        <Show when={props.snapshot.hasPersistence}>
          <button
            type="button"
            class={`pw-shell__btn ${escalated() ? "pw-shell__btn--retry" : "pw-shell__btn--suspend"}`}
            onClick={props.actions.suspend}
          >
            Save and come back later
          </button>
        </Show>
        <Show when={escalated() && !props.snapshot.hasPersistence}>
          <button type="button" class="pw-shell__btn pw-shell__btn--retry" onClick={props.actions.retry}>
            Try again
          </button>
        </Show>
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Default footer (navigation buttons)
// ---------------------------------------------------------------------------

function SolidFooter(props: {
  snapshot: PathSnapshot;
  actions: PathShellActions;
  backLabel: string;
  nextLabel: string;
  completeLabel: string;
  loadingLabel?: string;
  cancelLabel: string;
  hideCancel: boolean;
  footerLayout: "wizard" | "form";
}) {
  const isFormMode = () => props.footerLayout === "form";
  const isLoading = () => props.snapshot.status !== "idle";
  const submitLabel = () =>
    isLoading() && props.loadingLabel
      ? props.loadingLabel
      : props.snapshot.isLastStep
        ? props.completeLabel
        : props.nextLabel;

  return (
    <div class="pw-shell__footer">
      <div class="pw-shell__footer-left">
        {/* Form mode: Cancel on the left */}
        <Show when={isFormMode() && !props.hideCancel}>
          <button
            type="button"
            class="pw-shell__btn pw-shell__btn--cancel"
            disabled={isLoading()}
            onClick={props.actions.cancel}
          >
            {props.cancelLabel}
          </button>
        </Show>
        {/* Wizard mode: Back on the left */}
        <Show when={!isFormMode() && !props.snapshot.isFirstStep}>
          <button
            type="button"
            class="pw-shell__btn pw-shell__btn--back"
            disabled={isLoading() || !props.snapshot.canMovePrevious}
            onClick={props.actions.previous}
          >
            {props.backLabel}
          </button>
        </Show>
      </div>
      <div class="pw-shell__footer-right">
        {/* Wizard mode: Cancel on the right */}
        <Show when={!isFormMode() && !props.hideCancel}>
          <button
            type="button"
            class="pw-shell__btn pw-shell__btn--cancel"
            disabled={isLoading()}
            onClick={props.actions.cancel}
          >
            {props.cancelLabel}
          </button>
        </Show>
        {/* Both modes: Submit on the right */}
        <button
          type="button"
          class={`pw-shell__btn pw-shell__btn--next${isLoading() ? " pw-shell__btn--loading" : ""}`}
          disabled={isLoading()}
          onClick={props.actions.next}
        >
          {submitLabel()}
        </button>
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Re-export core types for convenience
// ---------------------------------------------------------------------------

export type {
  PathData,
  FieldErrors,
  PathDefinition,
  PathEvent,
  PathSnapshot,
  PathStep,
  PathStepContext,
  ProgressLayout,
  RootProgress,
  SerializedPathState,
} from "@daltonr/pathwrite-core";

export { PathEngine } from "@daltonr/pathwrite-core";
