// apps/angular-demos/demo-angular-nested/src/app/app.component.ts
import { Component } from "@angular/core";
import type { PathData } from "@daltonr/pathwrite-angular";
import { PathShellComponent, PathStepDirective } from "@daltonr/pathwrite-angular/shell";
import { employeeOnboardingPath } from "./onboarding.path";
import { ONBOARDING_INITIAL, type OnboardingData } from "./onboarding.types";
import type { EmployeeDetails } from "./employee-details.types";
import { LAPTOP_TYPES } from "./employee-details.types";
import { EnterNameComponent } from "./steps/enter-name.component";
import { DetailsStepComponent } from "./steps/details.component";
import { ConfirmStepComponent } from "./steps/confirm.component";

@Component({
  selector: "app-root",
  standalone: true,
  imports: [
    PathShellComponent,
    PathStepDirective,
    EnterNameComponent,
    DetailsStepComponent,
    ConfirmStepComponent,
  ],
  templateUrl: "./app.component.html",
  styleUrl: "./app.component.css",
})
export class AppComponent {
  protected readonly employeeOnboardingPath = employeeOnboardingPath;
  protected readonly initialData = ONBOARDING_INITIAL;

  protected isCompleted = false;
  protected isCancelled = false;
  protected completedData: OnboardingData | null = null;

  protected onComplete(data: PathData): void {
    this.completedData = data as OnboardingData;
    this.isCompleted = true;
  }

  protected onCancel(): void {
    this.isCancelled = true;
  }

  protected startOver(): void {
    this.isCompleted = false;
    this.isCancelled = false;
    this.completedData = null;
  }

  protected details(): EmployeeDetails {
    const d = this.completedData?.details as EmployeeDetails | undefined;
    return d ?? ({} as EmployeeDetails);
  }

  protected laptopLabel(val: string | undefined): string {
    const v = val ?? "macbook-pro";
    return LAPTOP_TYPES.find((l) => l.value === v)?.label ?? v;
  }

  protected yesNo(val: string | undefined): string {
    return val === "yes" ? "Yes" : "No";
  }

  protected activePerms(d: EmployeeDetails): string[] {
    return [
      d.permAdmin === "yes" ? "Admin" : null,
      d.permDev === "yes" ? "Developer" : null,
      d.permHR === "yes" ? "HR" : null,
      d.permFinance === "yes" ? "Finance" : null,
    ].filter((p): p is string => p !== null);
  }
}

<main class="page">
  <div class="page-header">
    <h1>Employee Onboarding</h1>
    <p class="subtitle">
      Nested PathShell demo — an independent Employee Details path runs inside Step 2. Data syncs to the outer
      path via <code>(event)</code>; the outer <code>fieldErrors</code> guard validates the inner data.
    </p>
  </div>

  <!-- ── Completed ──────────────────────────────────────────────────────────── -->
  @if (isCompleted && completedData) {
    <section class="result-panel success-panel">
      <div class="result-icon">&#127881;</div>
      <h2>Onboarding Complete!</h2>
      <p>
        <strong>{{ completedData.employeeName }}</strong> has been successfully onboarded.
      </p>

      <div class="summary">
        <div class="summary-section">
          <p class="summary-section__title">Personal</p>
          <div class="summary-row">
            <span class="summary-key">Name</span>
            <span>{{ details().firstName }} {{ details().lastName }}</span>
          </div>
          @if (details().phone) {
            <div class="summary-row">
              <span class="summary-key">Phone</span>
              <span>{{ details().phone }}</span>
            </div>
          }
        </div>

        <div class="summary-section">
          <p class="summary-section__title">Department</p>
          <div class="summary-row">
            <span class="summary-key">Department</span>
            <span>{{ details().department || "—" }}</span>
          </div>
          @if (details().manager) {
            <div class="summary-row">
              <span class="summary-key">Manager</span>
              <span>{{ details().manager }}</span>
            </div>
          }
          @if (details().office) {
            <div class="summary-row">
              <span class="summary-key">Office</span>
              <span>{{ details().office }}</span>
            </div>
          }
        </div>

        <div class="summary-section">
          <p class="summary-section__title">Equipment &amp; Roles</p>
          <div class="summary-row">
            <span class="summary-key">Laptop</span>
            <span>{{ laptopLabel(details().laptopType) }}</span>
          </div>
          <div class="summary-row">
            <span class="summary-key">Phone</span>
            <span>{{ yesNo(details().needsPhone) }}</span>
          </div>
          <div class="summary-row">
            <span class="summary-key">Job Title</span>
            <span>{{ details().jobTitle || "—" }}</span>
          </div>
          <div class="summary-row">
            <span class="summary-key">Permissions</span>
            <span>{{ activePerms(details()).length > 0 ? activePerms(details()).join(", ") : "None" }}</span>
          </div>
        </div>
      </div>

      <button type="button" class="btn-primary" (click)="startOver()">Onboard Another</button>
    </section>
  }

  <!-- ── Cancelled ──────────────────────────────────────────────────────────── -->
  @if (isCancelled) {
    <section class="result-panel cancel-panel">
      <div class="result-icon">&#10006;</div>
      <h2>Onboarding Cancelled</h2>
      <p>No record was created.</p>
      <button type="button" class="btn-secondary" (click)="startOver()">Try Again</button>
    </section>
  }

  <!-- ── Active wizard ──────────────────────────────────────────────────────── -->
  @if (!isCompleted && !isCancelled) {
    <pw-shell
      [path]="employeeOnboardingPath"
      [initialData]="initialData"
      completeLabel="Complete Onboarding"
      cancelLabel="Cancel"
      validationDisplay="inline"
      (complete)="onComplete($event)"
      (cancel)="onCancel()"
    >
      <ng-template pwStep="enter-name">
        <app-enter-name-step />
      </ng-template>

      <ng-template pwStep="employee-details">
        <app-details-step />
      </ng-template>

      <ng-template pwStep="confirm">
        <app-confirm-step />
      </ng-template>
    </pw-shell>
  }
</main>

// apps/vue-demos/demo-vue-nested/src/App.vue
<script setup lang="ts">
import { ref, computed } from "vue";
import { PathShell } from "@daltonr/pathwrite-vue";
import type { PathData } from "@daltonr/pathwrite-vue";
import { employeeOnboardingPath, ONBOARDING_INITIAL } from "./onboarding";
import type { OnboardingData } from "./onboarding";
import type { EmployeeDetails } from "./employee-details";
import { LAPTOP_TYPES } from "./employee-details";
import EnterNameStep from "./EnterNameStep.vue";
import EmployeeDetailsStep from "./EmployeeDetailsStep.vue";
import ConfirmStep from "./ConfirmStep.vue";

const isCompleted = ref(false);
const isCancelled = ref(false);
const completedData = ref<OnboardingData | null>(null);

function handleComplete(data: PathData) {
  completedData.value = data as OnboardingData;
  isCompleted.value = true;
}
function handleCancel() {
  isCancelled.value = true;
}
function startOver() {
  isCompleted.value = false;
  isCancelled.value = false;
  completedData.value = null;
}

function yesNo(val: string | undefined) {
  return val === "yes" ? "Yes" : "No";
}

const completedDetails = computed(() =>
  completedData.value ? ((completedData.value.details ?? {}) as EmployeeDetails) : null
);

const laptopLabel = computed(() => {
  const d = completedDetails.value;
  return d ? (LAPTOP_TYPES.find((l) => l.value === d.laptopType)?.label ?? d.laptopType) : "";
});

const activePerms = computed(() => {
  const d = completedDetails.value;
  if (!d) return [];
  return [
    d.permAdmin === "yes" && "Admin",
    d.permDev === "yes" && "Developer",
    d.permHR === "yes" && "HR",
    d.permFinance === "yes" && "Finance",
  ].filter(Boolean) as string[];
});
</script>

<template>
  <main class="page">
    <div class="page-header">
      <h1>Employee Onboarding</h1>
      <p class="subtitle">
        Nested PathShell demo — an independent Employee Details path runs inside Step 2. Data syncs to the
        parent via <code>@event</code>; the parent's <code>fieldErrors</code> guard validates the inner data.
      </p>
    </div>

    <!-- Completed -->
    <section v-if="isCompleted && completedData && completedDetails" class="result-panel success-panel">
      <div class="result-icon">🎉</div>
      <h2>Onboarding Complete!</h2>
      <p>
        <strong>{{ completedData.employeeName }}</strong> has been successfully onboarded.
      </p>
      <div class="summary">
        <div class="summary-section">
          <p class="summary-section__title">Personal</p>
          <div class="summary-row">
            <span class="summary-key">Name</span
            ><span>{{ completedDetails.firstName }} {{ completedDetails.lastName }}</span>
          </div>
          <div v-if="completedDetails.phone" class="summary-row">
            <span class="summary-key">Phone</span><span>{{ completedDetails.phone }}</span>
          </div>
        </div>
        <div class="summary-section">
          <p class="summary-section__title">Department</p>
          <div class="summary-row">
            <span class="summary-key">Department</span><span>{{ completedDetails.department }}</span>
          </div>
          <div v-if="completedDetails.manager" class="summary-row">
            <span class="summary-key">Manager</span><span>{{ completedDetails.manager }}</span>
          </div>
          <div v-if="completedDetails.office" class="summary-row">
            <span class="summary-key">Office</span><span>{{ completedDetails.office }}</span>
          </div>
        </div>
        <div class="summary-section">
          <p class="summary-section__title">Equipment &amp; Roles</p>
          <div class="summary-row">
            <span class="summary-key">Laptop</span><span>{{ laptopLabel }}</span>
          </div>
          <div class="summary-row">
            <span class="summary-key">Phone</span><span>{{ yesNo(completedDetails.needsPhone) }}</span>
          </div>
          <div class="summary-row">
            <span class="summary-key">Job Title</span><span>{{ completedDetails.jobTitle }}</span>
          </div>
          <div class="summary-row">
            <span class="summary-key">Permissions</span>
            <span>{{ activePerms.length > 0 ? activePerms.join(", ") : "None" }}</span>
          </div>
        </div>
      </div>
      <button class="btn-primary" @click="startOver">Onboard Another</button>
    </section>

    <!-- Cancelled -->
    <section v-if="isCancelled" class="result-panel cancel-panel">
      <div class="result-icon">✖</div>
      <h2>Onboarding Cancelled</h2>
      <p>No record was created.</p>
      <button class="btn-secondary" @click="startOver">Try Again</button>
    </section>

    <!-- Active wizard -->
    <PathShell
      v-if="!isCompleted && !isCancelled"
      :path="employeeOnboardingPath"
      :initial-data="ONBOARDING_INITIAL"
      complete-label="Complete Onboarding"
      cancel-label="Cancel"
      validation-display="inline"
      @complete="handleComplete"
      @cancel="handleCancel"
    >
      <template #enter-name><EnterNameStep /></template>
      <template #employee-details><EmployeeDetailsStep /></template>
      <template #confirm><ConfirmStep /></template>
    </PathShell>
  </main>
</template>
