// apps/vue-demos/demo-vue-wizard/src/ReviewStep.vue
<script setup lang="ts">
import { usePathContext } from "@daltonr/pathwrite-vue";
import { EXPERIENCE_LABELS, THEME_LABELS, type OnboardingData } from "./onboarding";

const { snapshot } = usePathContext<OnboardingData>();
</script>

<template>
  <div v-if="snapshot" class="form-body">
    <p class="step-intro">
      Everything look right? Click <strong>Complete Onboarding</strong> to finish,
      or use <strong>Previous</strong> to make changes.
    </p>

    <div class="review-section">
      <p class="section-title">Personal Info</p>
      <div class="review-card">
        <div class="review-row"><span class="review-key">Full Name</span><span>{{ snapshot.data.firstName }} {{ snapshot.data.lastName }}</span></div>
        <div class="review-row"><span class="review-key">Email</span><span>{{ snapshot.data.email }}</span></div>
      </div>
    </div>

    <div class="review-section">
      <p class="section-title">About You</p>
      <div class="review-card">
        <div class="review-row"><span class="review-key">Job Title</span><span>{{ snapshot.data.jobTitle }}</span></div>
        <div v-if="snapshot.data.company" class="review-row"><span class="review-key">Company</span><span>{{ snapshot.data.company }}</span></div>
        <div class="review-row"><span class="review-key">Experience</span><span>{{ EXPERIENCE_LABELS[snapshot.data.experience] ?? snapshot.data.experience }}</span></div>
      </div>
    </div>

    <div class="review-section">
      <p class="section-title">Preferences</p>
      <div class="review-card">
        <div class="review-row"><span class="review-key">Theme</span><span>{{ THEME_LABELS[snapshot.data.theme] ?? snapshot.data.theme }}</span></div>
        <div class="review-row">
          <span class="review-key">Notifications</span>
          <span :class="snapshot.data.notifications ? 'badge badge--on' : 'badge badge--off'">
            {{ snapshot.data.notifications ? '✓ Enabled' : '✗ Disabled' }}
          </span>
        </div>
      </div>
    </div>
  </div>
</template>

// apps/react-demos/demo-react-wizard/src/ReviewStep.tsx
import { usePathContext } from "@daltonr/pathwrite-react";
import { EXPERIENCE_LABELS, THEME_LABELS, type OnboardingData } from "./onboarding";

export function ReviewStep() {
  const { snapshot } = usePathContext<OnboardingData>();
  const data = snapshot?.data ?? {} as OnboardingData;

  return (
    <div className="form-body">
      <p className="step-intro">
        Everything look right? Click <strong>Complete Onboarding</strong> to finish,
        or use <strong>Previous</strong> to make changes.
      </p>

      <div className="review-section">
        <p className="section-title">Personal Info</p>
        <div className="review-card">
          <div className="review-row"><span className="review-key">Full Name</span><span>{data.firstName} {data.lastName}</span></div>
          <div className="review-row"><span className="review-key">Email</span><span>{data.email as string}</span></div>
        </div>
      </div>

      <div className="review-section">
        <p className="section-title">About You</p>
        <div className="review-card">
          <div className="review-row"><span className="review-key">Job Title</span><span>{data.jobTitle as string}</span></div>
          {data.company && <div className="review-row"><span className="review-key">Company</span><span>{data.company as string}</span></div>}
          <div className="review-row"><span className="review-key">Experience</span><span>{EXPERIENCE_LABELS[data.experience as string] ?? data.experience as string}</span></div>
        </div>
      </div>

      <div className="review-section">
        <p className="section-title">Preferences</p>
        <div className="review-card">
          <div className="review-row"><span className="review-key">Theme</span><span>{THEME_LABELS[data.theme as string] ?? data.theme as string}</span></div>
          <div className="review-row">
            <span className="review-key">Notifications</span>
            <span className={`badge ${data.notifications ? "badge--on" : "badge--off"}`}>
              {data.notifications ? "✓ Enabled" : "✗ Disabled"}
            </span>
          </div>
        </div>
      </div>
    </div>
  );
}
