// apps/react-demos/demo-react-subwizard/src/ApprovalReviewStep.tsx
import { usePathContext } from "@daltonr/pathwrite-react";
import { approvalSubPath, AVAILABLE_APPROVERS } from "./approval";
import type { DocumentData, ApprovalData, ApproverResult } from "./types";

export function ApprovalReviewStep() {
  const { snapshot, startSubPath } = usePathContext<DocumentData>();
  const snap = snapshot!;
  const data = snap.data;
  const errors = snap.hasAttemptedNext ? snap.fieldErrors : {};
  const results = (data.approvalResults ?? {}) as Record<string, ApproverResult>;

  const selectedApprovers = AVAILABLE_APPROVERS.filter((a) => (data.approvers as string[]).includes(a.id));

  const allDone = selectedApprovers.length > 0 && selectedApprovers.every((a) => !!results[a.id]?.decision);

  function launchReview(approverId: string, approverName: string) {
    const initialData: ApprovalData = {
      approverId,
      approverName,
      documentTitle: data.title ?? "",
      documentDescription: data.description ?? "",
      decision: "",
      comment: "",
    };
    startSubPath(approvalSubPath, initialData, { approverId });
  }

  return (
    <div className="form-body">
      <div className="doc-summary-card">
        <p className="doc-summary-label">Document</p>
        <p className="doc-summary-title">{data.title as string}</p>
        <p className="doc-summary-desc">{data.description as string}</p>
      </div>

      <div>
        <p className="pref-label">Approvers</p>
        <div className="approver-review-list">
          {selectedApprovers.map((approver) => (
            <div key={approver.id} className="approver-review-item">
              <span className="approver-avatar">{approver.name.charAt(0)}</span>
              <span className="approver-review-name">{approver.name}</span>
              {results[approver.id] ? (
                <span
                  className={`decision-badge ${results[approver.id].decision === "approved" ? "decision-badge--approved" : "decision-badge--rejected"}`}
                >
                  {results[approver.id].decision === "approved" ? "✓ Approved" : "✗ Rejected"}
                </span>
              ) : (
                <button
                  type="button"
                  className="btn-review"
                  disabled={snap.status !== "idle"}
                  onClick={() => launchReview(approver.id, approver.name)}
                >
                  Review →
                </button>
              )}
            </div>
          ))}
        </div>
      </div>

      {snap.hasAttemptedNext && errors._ && <p className="gate-message">⏳ {errors._}</p>}
      {allDone && (
        <p className="gate-message gate-message--done">
          ✓ All approvers have responded. Click Next to continue.
        </p>
      )}
    </div>
  );
}

// apps/svelte-demos/demo-svelte-subwizard/src/ApprovalReviewStep.svelte
<script lang="ts">
  import { usePathContext } from "@daltonr/pathwrite-svelte";
  import { approvalSubPath, AVAILABLE_APPROVERS } from "./approval";
  import type { DocumentData, ApprovalData, ApproverResult } from "./types";

  const ctx = usePathContext<DocumentData>();
  let errors = $derived(ctx.snapshot?.hasAttemptedNext ? ctx.snapshot.fieldErrors : {});
  let data = $derived(ctx.snapshot?.data);
  let results = $derived((data?.approvalResults ?? {}) as Record<string, ApproverResult>);

  let selectedApprovers = $derived(
    AVAILABLE_APPROVERS.filter((a) => ((data?.approvers ?? []) as string[]).includes(a.id))
  );

  let allDone = $derived(
    selectedApprovers.length > 0 && selectedApprovers.every((a) => !!results[a.id]?.decision)
  );

  function launchReview(approverId: string, approverName: string) {
    const initialData: ApprovalData = {
      approverId,
      approverName,
      documentTitle: data?.title ?? "",
      documentDescription: data?.description ?? "",
      decision: "",
      comment: "",
    };
    ctx.startSubPath(approvalSubPath, initialData, { approverId });
  }
</script>

{#if ctx.snapshot}
  <div class="form-body">
    <div class="doc-summary-card">
      <p class="doc-summary-label">Document</p>
      <p class="doc-summary-title">{data?.title}</p>
      <p class="doc-summary-desc">{data?.description}</p>
    </div>

    <div>
      <p class="pref-label">Approvers</p>
      <div class="approver-review-list">
        {#each selectedApprovers as approver}
          <div class="approver-review-item">
            <span class="approver-avatar">{approver.name.charAt(0)}</span>
            <span class="approver-review-name">{approver.name}</span>
            {#if results[approver.id]}
              <span
                class="decision-badge"
                class:decision-badge--approved={results[approver.id].decision === "approved"}
                class:decision-badge--rejected={results[approver.id].decision === "rejected"}
              >
                {results[approver.id].decision === "approved" ? "✓ Approved" : "✗ Rejected"}
              </span>
            {:else}
              <button
                type="button"
                class="btn-review"
                disabled={ctx.snapshot.status !== "idle"}
                onclick={() => launchReview(approver.id, approver.name)}
              >
                Review →
              </button>
            {/if}
          </div>
        {/each}
      </div>
    </div>

    {#if ctx.snapshot.hasAttemptedNext && errors._}
      <p class="gate-message">⏳ {errors._}</p>
    {/if}
    {#if allDone}
      <p class="gate-message gate-message--done">✓ All approvers have responded. Click Next to continue.</p>
    {/if}
  </div>
{/if}
