// apps/solid-demos/demo-solid-subwizard/src/CreateDocumentStep.tsx
import { createMemo, Show } from "solid-js";
import { usePathContext } from "@daltonr/pathwrite-solid";
import type { DocumentData } from "./types";

export default function CreateDocumentStep() {
  const ctx = usePathContext<DocumentData>();

  const errors = createMemo(() =>
    ctx.snapshot()?.hasAttemptedNext ? (ctx.snapshot()?.fieldErrors ?? {}) : {}
  );

  return (
    <Show when={ctx.snapshot()}>
      <div class="form-body">
        <p class="step-intro">Enter the details of the document you want to send for approval.</p>

        <div class="field" classList={{ "field--error": !!errors().title }}>
          <label for="title">
            Title <span class="required">*</span>
          </label>
          <input
            id="title"
            type="text"
            value={ctx.snapshot()?.data.title ?? ""}
            onInput={(e) => ctx.setData("title", e.currentTarget.value)}
            placeholder="e.g. Q1 Budget Report"
            autocomplete="off"
            autofocus
          />
          <Show when={errors().title}>
            <span class="field-error">{errors().title}</span>
          </Show>
        </div>

        <div class="field" classList={{ "field--error": !!errors().description }}>
          <label for="description">
            Description <span class="required">*</span>
          </label>
          <textarea
            id="description"
            rows={4}
            value={ctx.snapshot()?.data.description ?? ""}
            onInput={(e) => ctx.setData("description", e.currentTarget.value)}
            placeholder="Brief summary of the document and what needs to be approved..."
          />
          <Show when={errors().description}>
            <span class="field-error">{errors().description}</span>
          </Show>
        </div>
      </div>
    </Show>
  );
}

// apps/svelte-demos/demo-svelte-subwizard/src/CreateDocumentStep.svelte
<script lang="ts">
  import { usePathContext } from "@daltonr/pathwrite-svelte";
  import type { DocumentData } from "./types";

  const ctx = usePathContext<DocumentData>();
  let errors = $derived(ctx.snapshot?.hasAttemptedNext ? ctx.snapshot.fieldErrors : {});
</script>

{#if ctx.snapshot}
  <div class="form-body">
    <p class="step-intro">Enter the details of the document you want to send for approval.</p>

    <div class="field" class:field--error={errors.title}>
      <label for="title">Title <span class="required">*</span></label>
      <input id="title" type="text" value={ctx.snapshot.data.title ?? ""}
        oninput={(e) => ctx.setData("title", e.currentTarget.value)}
        placeholder="e.g. Q1 Budget Report" autocomplete="off" autofocus />
      {#if errors.title}<span class="field-error">{errors.title}</span>{/if}
    </div>

    <div class="field" class:field--error={errors.description}>
      <label for="description">Description <span class="required">*</span></label>
      <textarea id="description" value={ctx.snapshot.data.description ?? ""} rows={4}
        oninput={(e) => ctx.setData("description", e.currentTarget.value)}
        placeholder="Brief summary of the document and what needs to be approved..." />
      {#if errors.description}<span class="field-error">{errors.description}</span>{/if}
    </div>
  </div>
{/if}
