// apps/react-demos/demo-react-wizard/src/App.tsx
import { useState } from "react";
import { PathShell } from "@daltonr/pathwrite-react";
import type { PathData } from "@daltonr/pathwrite-react";
import { onboardingPath, INITIAL_DATA, EXPERIENCE_LABELS, THEME_LABELS, type OnboardingData } from "./onboarding";
import { PersonalInfoStep } from "./PersonalInfoStep";
import { AboutYouStep }     from "./AboutYouStep";
import { PreferencesStep }  from "./PreferencesStep";
import { ReviewStep }       from "./ReviewStep";

export default function App() {
  const [isCompleted,  setIsCompleted]  = useState(false);
  const [isCancelled,  setIsCancelled]  = useState(false);
  const [completedData, setCompletedData] = useState<OnboardingData | null>(null);

  function handleComplete(data: PathData) {
    setCompletedData(data as OnboardingData);
    setIsCompleted(true);
  }
  function handleCancel() { setIsCancelled(true); }
  function startOver() {
    setIsCompleted(false);
    setIsCancelled(false);
    setCompletedData(null);
  }

  return (
    <main className="page">
      <div className="page-header">
        <h1>User Onboarding</h1>
        <p className="subtitle">A 4-step wizard with guards, validation, and a final review.</p>
      </div>

      {/* Completed */}
      {isCompleted && completedData && (
        <section className="result-panel success-panel">
          <div className="result-icon">🎉</div>
          <h2>Welcome aboard!</h2>
          <p>Your profile has been set up, <strong>{completedData.firstName}</strong>.</p>
          <div className="summary">
            <div className="summary-section">
              <p className="summary-section__title">Personal Info</p>
              <div className="summary-row"><span className="summary-key">Name</span><span>{completedData.firstName} {completedData.lastName}</span></div>
              <div className="summary-row"><span className="summary-key">Email</span><span>{completedData.email}</span></div>
            </div>
            <div className="summary-section">
              <p className="summary-section__title">About You</p>
              <div className="summary-row"><span className="summary-key">Job Title</span><span>{completedData.jobTitle}</span></div>
              {completedData.company && <div className="summary-row"><span className="summary-key">Company</span><span>{completedData.company}</span></div>}
              <div className="summary-row"><span className="summary-key">Experience</span><span>{EXPERIENCE_LABELS[completedData.experience] ?? completedData.experience}</span></div>
            </div>
            <div className="summary-section">
              <p className="summary-section__title">Preferences</p>
              <div className="summary-row"><span className="summary-key">Theme</span><span>{THEME_LABELS[completedData.theme] ?? completedData.theme}</span></div>
              <div className="summary-row"><span className="summary-key">Notifications</span><span>{completedData.notifications ? "Enabled" : "Disabled"}</span></div>
            </div>
          </div>
          <button className="btn-primary" onClick={startOver}>Start Over</button>
        </section>
      )}

      {/* Cancelled */}
      {isCancelled && (
        <section className="result-panel cancel-panel">
          <div className="result-icon">✖</div>
          <h2>Onboarding Cancelled</h2>
          <p>Your profile was not saved.</p>
          <button className="btn-secondary" onClick={startOver}>Try Again</button>
        </section>
      )}

      {/* Active wizard */}
      {!isCompleted && !isCancelled && (
        <PathShell
          path={onboardingPath}
          initialData={INITIAL_DATA}
          completeLabel="Complete Onboarding"
          cancelLabel="Cancel"
          onComplete={handleComplete}
          onCancel={handleCancel}
          steps={{
            "personal-info": <PersonalInfoStep />,
            "about-you":     <AboutYouStep />,
            "preferences":   <PreferencesStep />,
            "review":        <ReviewStep />,
          }}
        />
      )}
    </main>
  );
}

// apps/solid-demos/demo-solid-wizard/src/App.tsx
import { createSignal, Show } from "solid-js";
import { PathShell } from "@daltonr/pathwrite-solid";
import type { PathData } from "@daltonr/pathwrite-solid";
import { onboardingPath, INITIAL_DATA, EXPERIENCE_LABELS, THEME_LABELS, type OnboardingData } from "./onboarding";
import PersonalInfoStep from "./PersonalInfoStep";
import AboutYouStep     from "./AboutYouStep";
import PreferencesStep  from "./PreferencesStep";
import ReviewStep       from "./ReviewStep";

export default function App() {
  const [isCompleted, setIsCompleted]   = createSignal(false);
  const [isCancelled, setIsCancelled]   = createSignal(false);
  const [completedData, setCompletedData] = createSignal<OnboardingData | null>(null);

  function handleComplete(data: PathData) {
    setCompletedData(data as OnboardingData);
    setIsCompleted(true);
  }

  function handleCancel() {
    setIsCancelled(true);
  }

  function startOver() {
    setIsCompleted(false);
    setIsCancelled(false);
    setCompletedData(null);
  }

  return (
    <main class="page">
      <div class="page-header">
        <h1>User Onboarding</h1>
        <p class="subtitle">A 4-step wizard with guards, validation, and a final review.</p>
      </div>

      {/* Completed */}
      <Show when={isCompleted() && completedData()}>
        {(data) => (
          <section class="result-panel success-panel">
            <div class="result-icon">🎉</div>
            <h2>Welcome aboard!</h2>
            <p>Your profile has been set up, <strong>{data().firstName}</strong>.</p>

            <div class="submitted-summary" style="max-width: 480px;">
              <div class="review-section">
                <p class="section-title">Personal Info</p>
                <div class="review-card">
                  <div class="review-row">
                    <span class="review-key">Name</span>
                    <span>{data().firstName} {data().lastName}</span>
                  </div>
                  <div class="review-row">
                    <span class="review-key">Email</span>
                    <span>{data().email}</span>
                  </div>
                </div>
              </div>

              <div class="review-section">
                <p class="section-title">About You</p>
                <div class="review-card">
                  <div class="review-row">
                    <span class="review-key">Job Title</span>
                    <span>{data().jobTitle}</span>
                  </div>
                  <Show when={data().company}>
                    <div class="review-row">
                      <span class="review-key">Company</span>
                      <span>{data().company}</span>
                    </div>
                  </Show>
                  <div class="review-row">
                    <span class="review-key">Experience</span>
                    <span>{EXPERIENCE_LABELS[data().experience] ?? data().experience}</span>
                  </div>
                </div>
              </div>

              <div class="review-section" style="margin-bottom: 0;">
                <p class="section-title">Preferences</p>
                <div class="review-card">
                  <div class="review-row">
                    <span class="review-key">Theme</span>
                    <span>{THEME_LABELS[data().theme] ?? data().theme}</span>
                  </div>
                  <div class="review-row">
                    <span class="review-key">Notifications</span>
                    <span class={data().notifications ? "badge badge--on" : "badge badge--off"}>
                      {data().notifications ? "✓ Enabled" : "✗ Disabled"}
                    </span>
                  </div>
                </div>
              </div>
            </div>

            <button class="btn-primary" onClick={startOver}>Start Over</button>
          </section>
        )}
      </Show>

      {/* Cancelled */}
      <Show when={isCancelled()}>
        <section class="result-panel cancel-panel">
          <div class="result-icon">✖</div>
          <h2>Onboarding Cancelled</h2>
          <p>Your profile was not saved.</p>
          <button class="btn-secondary" onClick={startOver}>Try Again</button>
        </section>
      </Show>

      {/* Active wizard */}
      <Show when={!isCompleted() && !isCancelled()}>
        <PathShell
          path={onboardingPath}
          initialData={INITIAL_DATA}
          completeLabel="Complete Onboarding"
          cancelLabel="Cancel"
          validationDisplay="inline"
          onComplete={handleComplete}
          onCancel={handleCancel}
          steps={{
            personalInfo: () => <PersonalInfoStep />,
            aboutYou:     () => <AboutYouStep />,
            preferences:  () => <PreferencesStep />,
            review:       () => <ReviewStep />,
          }}
        />
      </Show>
    </main>
  );
}
