// apps/svelte-demos/demo-svelte-stepchoice/src/ConfirmStep.svelte
<script lang="ts">
  import { usePathContext } from "@daltonr/pathwrite-svelte";
  import type { AddressData } from "./address-path";

  const ctx = usePathContext<AddressData>();

  const COUNTRY_NAMES: Record<string, string> = { US: "United States", IE: "Ireland" };
</script>

{#if ctx.snapshot}
  {@const d = ctx.snapshot.data}
  <div class="form-body">
    <p class="step-intro">
      Review your address below. Click <strong>Save Address</strong> to confirm, or use
      <strong>Previous</strong> to make changes.
    </p>

    <div>
      <p class="confirm-section-title">Selected Country</p>
      <div class="confirm-card">
        <div class="confirm-row">
          <span class="confirm-key">Country</span>
          <span>{COUNTRY_NAMES[d.country] ?? d.country}</span>
        </div>
      </div>
    </div>

    {#if d.country === "US"}
      <div>
        <p class="confirm-section-title">US Address</p>
        <div class="confirm-card">
          <div class="confirm-row">
            <span class="confirm-key">Street</span>
            <span>{d.streetAddress}{d.aptUnit ? `, ${d.aptUnit}` : ""}</span>
          </div>
          <div class="confirm-row">
            <span class="confirm-key">City</span>
            <span>{d.city}</span>
          </div>
          <div class="confirm-row">
            <span class="confirm-key">State</span>
            <span>{d.state}</span>
          </div>
          <div class="confirm-row">
            <span class="confirm-key">ZIP Code</span>
            <span>{d.zipCode}</span>
          </div>
        </div>
      </div>
    {:else}
      <div>
        <p class="confirm-section-title">Irish Address</p>
        <div class="confirm-card">
          <div class="confirm-row">
            <span class="confirm-key">Address Line 1</span>
            <span>{d.addressLine1}</span>
          </div>
          {#if d.addressLine2}
            <div class="confirm-row">
              <span class="confirm-key">Address Line 2</span>
              <span>{d.addressLine2}</span>
            </div>
          {/if}
          <div class="confirm-row">
            <span class="confirm-key">Town / City</span>
            <span>{d.town}</span>
          </div>
          <div class="confirm-row">
            <span class="confirm-key">County</span>
            <span>{d.county}</span>
          </div>
          {#if d.eircode}
            <div class="confirm-row">
              <span class="confirm-key">Eircode</span>
              <span>{d.eircode}</span>
            </div>
          {/if}
        </div>
      </div>
    {/if}
  </div>
{/if}

// apps/solid-demos/demo-solid-stepchoice/src/ConfirmStep.tsx
import { createMemo, Show } from "solid-js";
import type { PathSnapshot } from "@daltonr/pathwrite-core";
import type { AddressData } from "./address-path";

interface Props {
  snapshot: PathSnapshot;
}

const COUNTRY_NAMES: Record<string, string> = { US: "United States", IE: "Ireland" };

export default function ConfirmStep(props: Props) {
  const data = createMemo(() => props.snapshot.data as AddressData);
  const isUS = createMemo(() => data().country === "US");

  return (
    <div class="form-body">
      <p class="step-intro">
        Please review your address before confirming. The form used the <code>select</code> field to show the
        correct address variant for your country.
      </p>

      <div class="review-section">
        <p class="section-title">Country</p>
        <div class="review-card">
          <div class="review-row">
            <span class="review-key">Country</span>
            <span>{COUNTRY_NAMES[data().country] ?? data().country}</span>
          </div>
        </div>
      </div>

      <Show when={isUS()}>
        <div class="review-section">
          <p class="section-title">US Address</p>
          <div class="review-card">
            <div class="review-row">
              <span class="review-key">Street</span>
              <span>
                {data().streetAddress}
                {data().aptUnit ? `, ${data().aptUnit}` : ""}
              </span>
            </div>
            <div class="review-row">
              <span class="review-key">City</span>
              <span>{data().city}</span>
            </div>
            <div class="review-row">
              <span class="review-key">State</span>
              <span>{data().state}</span>
            </div>
            <div class="review-row">
              <span class="review-key">ZIP Code</span>
              <span>{data().zipCode}</span>
            </div>
          </div>
        </div>
      </Show>

      <Show when={!isUS()}>
        <div class="review-section">
          <p class="section-title">Irish Address</p>
          <div class="review-card">
            <div class="review-row">
              <span class="review-key">Address Line 1</span>
              <span>{data().addressLine1}</span>
            </div>
            <Show when={data().addressLine2}>
              <div class="review-row">
                <span class="review-key">Address Line 2</span>
                <span>{data().addressLine2}</span>
              </div>
            </Show>
            <div class="review-row">
              <span class="review-key">Town / City</span>
              <span>{data().town}</span>
            </div>
            <div class="review-row">
              <span class="review-key">County</span>
              <span>{data().county}</span>
            </div>
            <Show when={data().eircode}>
              <div class="review-row">
                <span class="review-key">Eircode</span>
                <span>{data().eircode}</span>
              </div>
            </Show>
          </div>
        </div>
      </Show>

      <p class="hint">
        Clicking <strong>Finish</strong> will complete the path. The <code>address</code> step used{" "}
        <code>select</code> to route to <code>{isUS() ? "address-us" : "address-ie"}</code> based on your
        country choice.
      </p>
    </div>
  );
}
