// apps/vue-demos/demo-vue-nested/src/EnterNameStep.vue
<script setup lang="ts">
import { computed } from "vue";
import { usePathContext } from "@daltonr/pathwrite-vue";
import type { OnboardingData } from "./onboarding";

const { snapshot, setData } = usePathContext<OnboardingData>();
const errors = computed(() => (snapshot.value.hasAttemptedNext ? snapshot.value.fieldErrors : {}));
</script>

<template>
  <div v-if="snapshot" class="form-body">
    <p class="step-intro">Enter the new employee's full name to begin their onboarding record.</p>
    <div class="field" :class="{ 'field--error': errors.employeeName }">
      <label for="employeeName">Full Name <span class="required">*</span></label>
      <input
        id="employeeName"
        type="text"
        :value="snapshot.data.employeeName"
        autofocus
        @input="setData('employeeName', ($event.target as HTMLInputElement).value)"
        placeholder="e.g. Jane Smith"
        autocomplete="name"
      />
      <span v-if="errors.employeeName" class="field-error">{{ errors.employeeName }}</span>
    </div>
  </div>
</template>

// apps/react-demos/demo-react-nested/src/EnterNameStep.tsx
import { usePathContext } from "@daltonr/pathwrite-react";
import type { OnboardingData } from "./onboarding";

export function EnterNameStep() {
  const { snapshot, setData } = usePathContext<OnboardingData>();
  const snap   = snapshot!;
  const errors = snap.hasAttemptedNext ? snap.fieldErrors : {};

  return (
    <div className="form-body">
      <p className="step-intro">
        Enter the new employee's full name to begin their onboarding record.
      </p>
      <div className={`field ${errors.employeeName ? "field--error" : ""}`}>
        <label htmlFor="employeeName">
          Full Name <span className="required">*</span>
        </label>
        <input
          id="employeeName"
          type="text"
          value={snap.data.employeeName ?? ""}
          autoFocus
          onChange={e => setData("employeeName", e.target.value)}
          placeholder="e.g. Jane Smith"
          autoComplete="name"
        />
        {errors.employeeName && (
          <span className="field-error">{errors.employeeName}</span>
        )}
      </div>
    </div>
  );
}
