// apps/react-demos/demo-react-stepchoice/src/CountryStep.tsx
import { usePathContext } from "@daltonr/pathwrite-react";
import type { AddressData } from "./address-path";

const COUNTRIES = [
  { code: "US", label: "United States" },
  { code: "IE", label: "Ireland" },
];

export function CountryStep() {
  const { snapshot, setData } = usePathContext<AddressData>();
  const snap   = snapshot!;
  const data   = snap.data;
  const errors = snap.hasAttemptedNext ? snap.fieldErrors : {};

  return (
    <div className="form-body">
      <p className="step-intro">Where are you based? We'll show you the right address form on the next step.</p>

      <div className="country-grid">
        {COUNTRIES.map(({ code, label }) => (
          <label key={code} className={`country-card ${data.country === code ? "country-card--selected" : ""}`}>
            <input
              type="radio"
              name="country"
              value={code}
              checked={data.country === code}
              onChange={() => setData("country", code)}
            />
            <span className="country-flag">{code === "US" ? "🇺🇸" : "🇮🇪"}</span>
            <span className="country-name">{label}</span>
          </label>
        ))}
      </div>

      {errors.country && <span className="field-error">{errors.country}</span>}
    </div>
  );
}

// apps/svelte-demos/demo-svelte-stepchoice/src/CountryStep.svelte
<script lang="ts">
  import { usePathContext } from "@daltonr/pathwrite-svelte";
  import type { AddressData } from "./address-path";

  const ctx = usePathContext<AddressData>();
  let errors = $derived(ctx.snapshot?.hasAttemptedNext ? ctx.snapshot.fieldErrors : {});
</script>

{#if ctx.snapshot}
  <div class="form-body">
    <p class="step-intro">Select your country. We'll show the right address form for your location.</p>

    <div>
      <div class="country-cards">
        <label class="country-card">
          <input
            type="radio"
            name="country"
            value="US"
            checked={ctx.snapshot.data.country === "US"}
            onchange={() => ctx.setData("country", "US")}
          />
          <span class="country-flag">🇺🇸</span>
          <span class="country-name">United States</span>
        </label>
        <label class="country-card">
          <input
            type="radio"
            name="country"
            value="IE"
            checked={ctx.snapshot.data.country === "IE"}
            onchange={() => ctx.setData("country", "IE")}
          />
          <span class="country-flag">🇮🇪</span>
          <span class="country-name">Ireland</span>
        </label>
      </div>
      {#if errors.country}
        <p class="country-error">{errors.country}</p>
      {/if}
    </div>
  </div>
{/if}
