// apps/react-demos/demo-react-storage/src/BackgroundStep.tsx
import { usePathContext } from "@daltonr/pathwrite-react";
import type { ProfileSubData } from "./wizard";

export function BackgroundStep() {
  const { snapshot, setData } = usePathContext<ProfileSubData>();
  const snap = snapshot!;
  const data = snap.data;
  const errors = snap.hasAttemptedNext ? snap.fieldErrors : {};

  return (
    <div className="form-body">
      <div className="subwizard-context">
        <p className="subwizard-for">Completing profile for</p>
        <p className="subwizard-name">
          {data.memberName as string}
          {data.memberRole && <span className="subwizard-role"> — {data.memberRole as string}</span>}
        </p>
      </div>

      <div className={`field ${errors.department ? "field--error" : ""}`}>
        <label htmlFor="department">
          Department <span className="required">*</span>
        </label>
        <input
          id="department"
          type="text"
          placeholder="e.g. Engineering, Design, Product, Marketing…"
          value={(data.department as string) ?? ""}
          autoFocus
          onChange={(e) => setData("department", e.target.value)}
        />
        {errors.department && <span className="field-error">{errors.department}</span>}
      </div>

      <div className={`field ${errors.startDate ? "field--error" : ""}`}>
        <label htmlFor="start-date">
          Start Date <span className="required">*</span>
        </label>
        <input
          id="start-date"
          type="date"
          value={(data.startDate as string) ?? ""}
          onChange={(e) => setData("startDate", e.target.value)}
        />
        {errors.startDate && <span className="field-error">{errors.startDate}</span>}
      </div>

      <div className={`field ${errors.bio ? "field--error" : ""}`}>
        <label htmlFor="bio">
          Short Bio <span className="required">*</span>
          <span className="field-hint">Introduce this person to the team</span>
        </label>
        <textarea
          id="bio"
          rows={6}
          placeholder="Describe their background, previous experience, what drew them to this role, and what they'll bring to the team."
          value={(data.bio as string) ?? ""}
          onChange={(e) => setData("bio", e.target.value)}
        />
        {errors.bio && <span className="field-error">{errors.bio}</span>}
      </div>
    </div>
  );
}

// apps/svelte-demos/demo-svelte-storage/src/BackgroundStep.svelte
<script lang="ts">
  import { usePathContext } from "@daltonr/pathwrite-svelte";
  import type { ProfileSubData } from "./wizard";

  const ctx = usePathContext<ProfileSubData>();
  let errors = $derived(ctx.snapshot?.hasAttemptedNext ? ctx.snapshot.fieldErrors : {});
</script>

{#if ctx.snapshot}
  {@const d = ctx.snapshot.data}
  <div class="form-body">
    <!-- Who we're filling in for -->
    <div class="subwizard-context">
      <p class="subwizard-for">Completing profile for</p>
      <p class="subwizard-name">
        {d.memberName}
        {#if d.memberRole}<span class="subwizard-role"> — {d.memberRole}</span>{/if}
      </p>
    </div>

    <!-- Department -->
    <div class="field" class:field--error={errors.department}>
      <label for="department">Department <span class="required">*</span></label>
      <input
        id="department"
        type="text"
        placeholder="e.g. Engineering, Design, Product, Marketing…"
        value={d.department ?? ""}
        oninput={(e) => ctx.setData("department", e.currentTarget.value)}
      />
      {#if errors.department}<p class="field-error">{errors.department}</p>{/if}
    </div>

    <!-- Start date -->
    <div class="field" class:field--error={errors.startDate}>
      <label for="start-date">Start Date <span class="required">*</span></label>
      <input
        id="start-date"
        type="date"
        value={d.startDate ?? ""}
        onchange={(e) => ctx.setData("startDate", e.currentTarget.value)}
      />
      {#if errors.startDate}<p class="field-error">{errors.startDate}</p>{/if}
    </div>

    <!-- Bio -->
    <div class="field" class:field--error={errors.bio}>
      <label for="bio">
        Short Bio <span class="required">*</span>
        <span class="field-hint">Introduce this person to the team</span>
      </label>
      <textarea
        id="bio"
        rows="6"
        placeholder="Describe their background, previous experience, what drew them to this role, and what they'll bring to the team."
        value={d.bio ?? ""}
        oninput={(e) => ctx.setData("bio", e.currentTarget.value)}></textarea>
      {#if errors.bio}<p class="field-error">{errors.bio}</p>{/if}
    </div>
  </div>
{/if}
