// apps/react-demos/demo-react-async/src/ReviewStep.tsx
import { usePathContext } from "@daltonr/pathwrite-react";
import type { ApplicationData } from "@daltonr/pathwrite-demo-workflow-job-application";

export function ReviewStep() {
  const { snapshot } = usePathContext<ApplicationData>();
  const snap = snapshot!;
  const data = snap.data;

  return (
    <div className="form-body">
      <p className="step-intro">
        All async checks passed. Review your application before submitting.
      </p>

      <div className="eligibility-summary">
        <div className="summary-row">
          <span className="summary-key">Role</span>
          <span>{data.roleId as string}</span>
        </div>
        <div className="summary-row">
          <span className="summary-key">Experience</span>
          <span>{data.yearsExperience} years</span>
        </div>
        <div className="summary-row">
          <span className="summary-key">Skills</span>
          <span>{data.skills as string}</span>
        </div>
        {data.coverLetter && (
          <div className="summary-row">
            <span className="summary-key">Cover Letter</span>
            <span>{data.coverLetter as string}</span>
          </div>
        )}
      </div>
    </div>
  );
}

// apps/vue-demos/demo-vue-async/src/ReviewStep.vue
<script setup lang="ts">
import { usePathContext } from "@daltonr/pathwrite-vue";
import type { ApplicationData } from "@daltonr/pathwrite-demo-workflow-job-application";

const { snapshot } = usePathContext<ApplicationData>();
</script>

<template>
  <div v-if="snapshot" class="form-body">
    <p class="step-intro">All async checks passed. Review your application before submitting.</p>

    <div class="eligibility-summary">
      <div class="summary-row">
        <span class="summary-key">Role</span>
        <span>{{ snapshot.data.roleId }}</span>
      </div>
      <div class="summary-row">
        <span class="summary-key">Experience</span>
        <span>{{ snapshot.data.yearsExperience }} years</span>
      </div>
      <div class="summary-row">
        <span class="summary-key">Skills</span>
        <span>{{ snapshot.data.skills }}</span>
      </div>
      <div v-if="snapshot.data.coverLetter" class="summary-row">
        <span class="summary-key">Cover Letter</span>
        <span>{{ snapshot.data.coverLetter }}</span>
      </div>
    </div>
  </div>
</template>
