// packages/solid-adapter/src/index.tsx
import {
  createSignal,
  onCleanup,
  onMount,
  createContext,
  useContext,
  createEffect,
  For,
  Show,
  type Component,
  type JSX,
  type Accessor,
} from "solid-js";
import {
  PathData,
  PathDefinition,
  PathEngine,
  PathEvent,
  PathSnapshot,
  ProgressLayout,
  RootProgress,
  formatFieldKey,
  errorPhaseMessage,
} from "@daltonr/pathwrite-core";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface UsePathOptions {
  /**
   * An externally-managed `PathEngine` to subscribe to — for example, the engine
   * returned by `createPersistedEngine()` from `@daltonr/pathwrite-store`.
   *
   * When provided:
   * - `usePath` will **not** create its own engine.
   * - The snapshot is seeded immediately from the engine's current state.
   * - The engine lifecycle (start / cleanup) is the **caller's responsibility**.
   * - `PathShell` will skip its own `autoStart` call.
   */
  engine?: PathEngine;
  /** Called for every engine event (stateChanged, completed, cancelled, resumed). */
  onEvent?: (event: PathEvent) => void;
}

export interface UsePathReturn<TData extends PathData = PathData> {
  /**
   * Reactive snapshot accessor. Call `snapshot()` to read the current value.
   * Automatically tracked as a reactive dependency when read inside JSX or effects.
   */
  snapshot: Accessor<PathSnapshot<TData> | null>;
  /** Start (or restart) a path. */
  start: (path: PathDefinition<any>, initialData?: PathData) => Promise<void>;
  /** Push a sub-path onto the stack. Requires an active path. Pass an optional `meta` object for correlation — it is returned unchanged to the parent step's `onSubPathComplete` / `onSubPathCancel` hooks. */
  startSubPath: (path: PathDefinition<any>, initialData?: PathData, meta?: Record<string, unknown>) => Promise<void>;
  /** Advance one step. Completes the path on the last step. */
  next: () => Promise<void>;
  /** Go back one step. No-op when already on the first step of a top-level path. Pops back to the parent path when on the first step of a sub-path. */
  previous: () => Promise<void>;
  /** Cancel the active path (or sub-path). */
  cancel: () => Promise<void>;
  /** Jump directly to a step by ID. Calls onLeave / onEnter but bypasses guards and shouldSkip. */
  goToStep: (stepId: string) => Promise<void>;
  /** Jump directly to a step by ID, checking the current step's canMoveNext (forward) or canMovePrevious (backward) guard first. Navigation is blocked if the guard returns false. */
  goToStepChecked: (stepId: string) => Promise<void>;
  /** Update a single data value; triggers re-renders via stateChanged. When `TData` is specified, `key` and `value` are type-checked against your data shape. */
  setData: <K extends string & keyof TData>(key: K, value: TData[K]) => Promise<void>;
  /** Reset the current step's data to what it was when the step was entered. Useful for "Clear" or "Reset" buttons. */
  resetStep: () => Promise<void>;
  /**
   * Tear down any active path (without firing hooks) and immediately start the
   * given path fresh. Safe to call whether or not a path is currently active.
   * Use for "Start over" / retry flows without remounting the component.
   */
  restart: () => Promise<void>;
  /** Re-runs the operation that set `snapshot().error`. Increments `retryCount` on repeated failure. No-op when there is no pending error. */
  retry: () => Promise<void>;
  /** Pauses the path with intent to return. Emits `suspended`. All state is preserved. */
  suspend: () => Promise<void>;
  /** Trigger inline validation on all steps without navigating. Sets `snapshot().hasValidated`. */
  validate: () => void;
}

// ---------------------------------------------------------------------------
// usePath composable
// ---------------------------------------------------------------------------

export function usePath<TData extends PathData = PathData>(options?: UsePathOptions): UsePathReturn<TData> {
  const engine = options?.engine ?? new PathEngine();

  const [snapshot, setSnapshot] = createSignal<PathSnapshot<TData> | null>(
    engine.snapshot() as PathSnapshot<TData> | null,
    // always notify — PathEngine produces new snapshot objects on every event
    { equals: false }
  );

  const unsubscribe = engine.subscribe((event: PathEvent) => {
    if (event.type === "stateChanged" || event.type === "resumed") {
      setSnapshot(event.snapshot as PathSnapshot<TData>);
    } else if (event.type === "completed" || event.type === "cancelled") {
      setSnapshot(engine.snapshot() as PathSnapshot<TData> | null);
    }
    options?.onEvent?.(event);
  });

  onCleanup(unsubscribe);

  const start = (path: PathDefinition<any>, initialData: PathData = {}): Promise<void> =>
    engine.start(path, initialData);

  const startSubPath = (path: PathDefinition<any>, initialData: PathData = {}, meta?: Record<string, unknown>): Promise<void> =>
    engine.startSubPath(path, initialData, meta);

  const next = (): Promise<void> => engine.next();
  const previous = (): Promise<void> => engine.previous();
  const cancel = (): Promise<void> => engine.cancel();
  const goToStep = (stepId: string): Promise<void> => engine.goToStep(stepId);
  const goToStepChecked = (stepId: string): Promise<void> => engine.goToStepChecked(stepId);

  const setData = (<K extends string & keyof TData>(key: K, value: TData[K]): Promise<void> =>
    engine.setData(key, value as unknown)) as UsePathReturn<TData>["setData"];

  const resetStep = (): Promise<void> => engine.resetStep();
  const restart = (): Promise<void> => engine.restart();
  const retry = (): Promise<void> => engine.retry();
  const suspend = (): Promise<void> => engine.suspend();
  const validate = (): void => engine.validate();

  return { snapshot, start, startSubPath, next, previous, cancel, goToStep, goToStepChecked, setData, resetStep, restart, retry, suspend, validate };
}

// ---------------------------------------------------------------------------
// Context — provide / useContext
// ---------------------------------------------------------------------------

interface PathContextValue {
  path: UsePathReturn;
  services: unknown;
}

const PathContext = createContext<PathContextValue | undefined>(undefined);

/**
 * Access the nearest `PathShell`'s path instance and optional services object.
 * Throws if used outside of a PathShell component.
 *
 * Both generics are type-level assertions, not runtime guarantees:
 * - `TData` narrows `snapshot().data`
 * - `TServices` types the `services` value — must match what was passed to `PathShell`
 */
export function usePathContext<TData extends PathData = PathData, TServices = unknown>(): Omit<UsePathReturn<TData>, "snapshot"> & { snapshot: Accessor<PathSnapshot<TData>>; services: TServices } {
  const ctx = useContext(PathContext);
  if (!ctx) {
    throw new Error("usePathContext must be used within a PathShell component.");
  }
  return {
    ...(ctx.path as unknown as Omit<UsePathReturn<TData>, "snapshot"> & { snapshot: Accessor<PathSnapshot<TData>> }),
    services: ctx.services as TServices,
  };
}

// ---------------------------------------------------------------------------
// Default UI — PathShell
// ---------------------------------------------------------------------------

export interface PathShellActions {
  next: () => Promise<void>;
  previous: () => Promise<void>;
  cancel: () => Promise<void>;
  goToStep: (stepId: string) => Promise<void>;
  goToStepChecked: (stepId: string) => Promise<void>;
  setData: (key: string, value: unknown) => Promise<void>;
  restart: () => Promise<void>;
  retry: () => Promise<void>;
  suspend: () => Promise<void>;
}

export interface PathShellProps {
  path: PathDefinition<any>;
  /**
   * An externally-managed engine — for example, the engine returned by
   * `createPersistedEngine()`. When supplied, `PathShell` will skip its own
   * `start()` call and drive the UI from the provided engine instead.
   */
  engine?: PathEngine;
  initialData?: PathData;
  autoStart?: boolean;
  /**
   * Step render functions keyed by step ID (or `formId` for StepChoice steps).
   * ```tsx
   * <PathShell steps={{ details: (snap) => <DetailsStep snapshot={snap} />, review: (snap) => <ReviewStep snapshot={snap} /> }} />
   * ```
   */
  steps?: Record<string, (snapshot: PathSnapshot) => JSX.Element>;
  onComplete?: (data: PathData) => void;
  onCancel?: (data: PathData) => void;
  onEvent?: (event: PathEvent) => void;
  renderHeader?: (snapshot: PathSnapshot) => JSX.Element;
  renderFooter?: (snapshot: PathSnapshot, actions: PathShellActions) => JSX.Element;
  backLabel?: string;
  nextLabel?: string;
  completeLabel?: string;
  loadingLabel?: string;
  cancelLabel?: string;
  hideCancel?: boolean;
  hideProgress?: boolean;
  /** If true, hide the footer (navigation buttons). The error panel is still shown on async failure regardless of this prop. */
  hideFooter?: boolean;
  /**
   * Footer layout mode:
   * - `"auto"` (default): Uses "form" for single-step top-level paths, "wizard" otherwise.
   * - `"wizard"`: Back button on left, Cancel and Submit together on right.
   * - `"form"`: Cancel on left, Submit alone on right. Back button never shown.
   */
  footerLayout?: "wizard" | "form" | "auto";
  /**
   * Controls whether the shell renders its auto-generated field-error summary box.
   * - `"summary"` (default): Shell renders the labeled error list below the step body.
   * - `"inline"`: Suppress the summary — handle errors inside the step component instead.
   * - `"both"`: Render the shell summary AND whatever the step renders.
   */
  validationDisplay?: "summary" | "inline" | "both";
  /**
   * Controls how progress bars are arranged when a sub-path is active.
   * - `"merged"` (default): Root and sub-path bars in one card.
   * - `"split"`: Root and sub-path bars as separate cards.
   * - `"rootOnly"`: Only the root bar — sub-path bar hidden.
   * - `"activeOnly"`: Only the active (sub-path) bar — root bar hidden.
   */
  progressLayout?: ProgressLayout;
  /**
   * Services object passed through context to all step components.
   * Step components access it via `usePathContext<TData, TServices>()`.
   */
  services?: object | null;
  /** When true, calls `validate()` on the engine so all steps show inline errors simultaneously. Useful when this shell is nested inside a step of an outer shell: bind to the outer snapshot's `hasAttemptedNext`. */
  validateWhen?: boolean;
  class?: string;
  /**
   * Content rendered when `snapshot.status === "completed"` (i.e. after the path
   * finishes with `completionBehaviour: "stayOnFinal"`). Defaults to a simple
   * "All done." panel with a Restart button.
   */
  completionContent?: (snapshot: PathSnapshot) => JSX.Element;
}

export const PathShell: Component<PathShellProps> = (props) => {
  const pathReturn = usePath({
    engine: props.engine,
    onEvent(event) {
      props.onEvent?.(event);
      if (event.type === "completed") props.onComplete?.(event.data as PathData);
      if (event.type === "cancelled") props.onCancel?.(event.data as PathData);
    },
  });

  const { snapshot, start, next, previous, cancel, goToStep, goToStepChecked, setData, restart, retry, suspend, validate } = pathReturn;

  onMount(() => {
    if (props.autoStart !== false && !props.engine) {
      start(props.path, props.initialData ?? {});
    }
  });

  createEffect(() => {
    if (props.validateWhen) validate();
  });

  const contextValue: PathContextValue = { path: pathReturn, services: props.services ?? null };

  const actions: PathShellActions = {
    next, previous, cancel, goToStep, goToStepChecked,
    setData: (key, value) => setData(key as any, value as any),
    restart: () => restart(),
    retry: () => retry(),
    suspend: () => suspend(),
  };

  // Convenience — non-null snapshot, only valid inside <Show when={snapshot()}>
  const snap = () => snapshot()!;

  const shellClass = () => {
    const base = "pw-shell";
    const layout = props.progressLayout;
    const mod = layout && layout !== "merged" ? ` pw-shell--progress-${layout}` : "";
    return props.class ? `${base}${mod} ${props.class}` : `${base}${mod}`;
  };

  const showRoot = () => !props.hideProgress && !!snap().rootProgress && props.progressLayout !== "activeOnly";
  const showActive = () => !props.hideProgress && (snap().stepCount > 1 || snap().nestingLevel > 0) && props.progressLayout !== "rootOnly";

  const stepContent = () => {
    const s = snap();
    const key = s.formId ?? s.stepId;
    const render = props.steps?.[key];
    return render ? render(s) : null;
  };

  const showValidation = () =>
    props.validationDisplay !== "inline" &&
    (snap().hasAttemptedNext || snap().hasValidated) &&
    Object.keys(snap().fieldErrors).length > 0;

  const showWarnings = () =>
    props.validationDisplay !== "inline" &&
    Object.keys(snap().fieldWarnings).length > 0;

  const showBlockingError = () =>
    props.validationDisplay !== "inline" &&
    (snap().hasAttemptedNext || snap().hasValidated) &&
    !!snap().blockingError;

  const resolvedFooterLayout = () => {
    const fl = props.footerLayout ?? "auto";
    if (fl !== "auto") return fl;
    return snap().stepCount === 1 && snap().nestingLevel === 0 ? "form" : "wizard";
  };

  return (
    <PathContext.Provider value={contextValue}>
      <Show
        when={snapshot()}
        fallback={
          <div class="pw-shell">
            <div class="pw-shell__empty">
              <p>No active path.</p>
              <Show when={props.autoStart === false}>
                <button
                  type="button"
                  class="pw-shell__start-btn"
                  onClick={() => start(props.path, props.initialData ?? {})}
                >
                  Start
                </button>
              </Show>
            </div>
          </div>
        }
      >
        <div class={shellClass()}>
          {/* Root progress — persistent top-level bar visible during sub-paths */}
          <Show when={showRoot()}>
            <SolidRootProgress root={snap().rootProgress!} />
          </Show>
          {/* Header — progress (active path) */}
          <Show when={showActive()}>
            {props.renderHeader
              ? props.renderHeader(snap())
              : <SolidHeader snapshot={snap()} />}
          </Show>
          {/* Completion panel — shown when path finishes with stayOnFinal */}
          <Show when={snap().status === "completed"}>
            <div class="pw-shell__body">
              {props.completionContent
                ? props.completionContent(snap())
                : (
                  <div class="pw-shell__completion">
                    <p class="pw-shell__completion-message">All done.</p>
                    <button
                      type="button"
                      class="pw-shell__completion-restart"
                      onClick={() => restart()}
                    >
                      Start over
                    </button>
                  </div>
                )
              }
            </div>
          </Show>
          {/* Body — step content (hidden when completed) */}
          <Show when={snap().status !== "completed"}>
          <div class="pw-shell__body">{stepContent()}</div>
          {/* Validation messages */}
          <Show when={showValidation()}>
            <ul class="pw-shell__validation">
              <For each={Object.entries(snap().fieldErrors)}>
                {([key, msg]) => (
                  <li class="pw-shell__validation-item">
                    <Show when={key !== "_"}>
                      <span class="pw-shell__validation-label">{formatFieldKey(key)}</span>
                    </Show>
                    {msg}
                  </li>
                )}
              </For>
            </ul>
          </Show>
          {/* Warning messages — non-blocking, shown immediately */}
          <Show when={showWarnings()}>
            <ul class="pw-shell__warnings">
              <For each={Object.entries(snap().fieldWarnings)}>
                {([key, msg]) => (
                  <li class="pw-shell__warnings-item">
                    <Show when={key !== "_"}>
                      <span class="pw-shell__warnings-label">{formatFieldKey(key)}</span>
                    </Show>
                    {msg}
                  </li>
                )}
              </For>
            </ul>
          </Show>
          {/* Blocking error */}
          <Show when={showBlockingError()}>
            <p class="pw-shell__blocking-error">{snap().blockingError}</p>
          </Show>
          {/* Error panel or footer */}
          <Show
            when={snap().status === "error" && snap().error}
            fallback={
              <Show when={!props.hideFooter}>
                {props.renderFooter
                  ? props.renderFooter(snap(), actions)
                  : <SolidFooter
                      snapshot={snap()}
                      actions={actions}
                      backLabel={props.backLabel ?? "Previous"}
                      nextLabel={props.nextLabel ?? "Next"}
                      completeLabel={props.completeLabel ?? "Complete"}
                      loadingLabel={props.loadingLabel}
                      cancelLabel={props.cancelLabel ?? "Cancel"}
                      hideCancel={props.hideCancel ?? false}
                      footerLayout={resolvedFooterLayout()}
                    />
                }
              </Show>
            }
          >
            <SolidErrorPanel snapshot={snap()} actions={actions} />
          </Show>
          </Show>{/* end status !== completed */}
        </div>
      </Show>
    </PathContext.Provider>
  );
};

// ---------------------------------------------------------------------------
// Root progress
// ---------------------------------------------------------------------------

function SolidRootProgress(props: { root: RootProgress }) {
  return (
    <div class="pw-shell__root-progress">
      <div class="pw-shell__steps">
        <For each={props.root.steps}>
          {(step, i) => (
            <div class={`pw-shell__step pw-shell__step--${step.status}`}>
              <span class="pw-shell__step-dot">
                {step.status === "completed" ? "✓" : String(i() + 1)}
              </span>
              <span class="pw-shell__step-label">{step.title ?? step.id}</span>
            </div>
          )}
        </For>
      </div>
      <div class="pw-shell__track">
        <div class="pw-shell__track-fill" style={{ width: `${props.root.progress * 100}%` }} />
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Default header (progress indicator)
// ---------------------------------------------------------------------------

function SolidHeader(props: { snapshot: PathSnapshot }) {
  return (
    <div class="pw-shell__header">
      <div class="pw-shell__steps">
        <For each={props.snapshot.steps}>
          {(step, i) => (
            <div class={`pw-shell__step pw-shell__step--${step.status}`}>
              <span class="pw-shell__step-dot">
                {step.status === "completed" ? "✓" : String(i() + 1)}
              </span>
              <span class="pw-shell__step-label">{step.title ?? step.id}</span>
            </div>
          )}
        </For>
      </div>
      <div class="pw-shell__track">
        <div class="pw-shell__track-fill" style={{ width: `${props.snapshot.progress * 100}%` }} />
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Error panel
// ---------------------------------------------------------------------------

function SolidErrorPanel(props: { snapshot: PathSnapshot; actions: PathShellActions }) {
  const error = () => props.snapshot.error!;
  const escalated = () => error().retryCount >= 2;
  const title = () => escalated() ? "Still having trouble." : "Something went wrong.";
  const phaseMsg = () => errorPhaseMessage(error().phase);

  return (
    <div class="pw-shell__error">
      <div class="pw-shell__error-title">{title()}</div>
      <div class="pw-shell__error-message">
        {phaseMsg()}{error().message ? ` ${error().message}` : ""}
      </div>
      <div class="pw-shell__error-actions">
        <Show when={!escalated()}>
          <button type="button" class="pw-shell__btn pw-shell__btn--retry" onClick={props.actions.retry}>
            Try again
          </button>
        </Show>
        <Show when={props.snapshot.hasPersistence}>
          <button
            type="button"
            class={`pw-shell__btn ${escalated() ? "pw-shell__btn--retry" : "pw-shell__btn--suspend"}`}
            onClick={props.actions.suspend}
          >
            Save and come back later
          </button>
        </Show>
        <Show when={escalated() && !props.snapshot.hasPersistence}>
          <button type="button" class="pw-shell__btn pw-shell__btn--retry" onClick={props.actions.retry}>
            Try again
          </button>
        </Show>
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Default footer (navigation buttons)
// ---------------------------------------------------------------------------

function SolidFooter(props: {
  snapshot: PathSnapshot;
  actions: PathShellActions;
  backLabel: string;
  nextLabel: string;
  completeLabel: string;
  loadingLabel?: string;
  cancelLabel: string;
  hideCancel: boolean;
  footerLayout: "wizard" | "form";
}) {
  const isFormMode = () => props.footerLayout === "form";
  const isLoading = () => props.snapshot.status !== "idle";
  const submitLabel = () =>
    isLoading() && props.loadingLabel
      ? props.loadingLabel
      : props.snapshot.isLastStep
        ? props.completeLabel
        : props.nextLabel;

  return (
    <div class="pw-shell__footer">
      <div class="pw-shell__footer-left">
        {/* Form mode: Cancel on the left */}
        <Show when={isFormMode() && !props.hideCancel}>
          <button
            type="button"
            class="pw-shell__btn pw-shell__btn--cancel"
            disabled={isLoading()}
            onClick={props.actions.cancel}
          >
            {props.cancelLabel}
          </button>
        </Show>
        {/* Wizard mode: Back on the left */}
        <Show when={!isFormMode() && !props.snapshot.isFirstStep}>
          <button
            type="button"
            class="pw-shell__btn pw-shell__btn--back"
            disabled={isLoading() || !props.snapshot.canMovePrevious}
            onClick={props.actions.previous}
          >
            {props.backLabel}
          </button>
        </Show>
      </div>
      <div class="pw-shell__footer-right">
        {/* Wizard mode: Cancel on the right */}
        <Show when={!isFormMode() && !props.hideCancel}>
          <button
            type="button"
            class="pw-shell__btn pw-shell__btn--cancel"
            disabled={isLoading()}
            onClick={props.actions.cancel}
          >
            {props.cancelLabel}
          </button>
        </Show>
        {/* Both modes: Submit on the right */}
        <button
          type="button"
          class={`pw-shell__btn pw-shell__btn--next${isLoading() ? " pw-shell__btn--loading" : ""}`}
          disabled={isLoading()}
          onClick={props.actions.next}
        >
          {submitLabel()}
        </button>
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Re-export core types for convenience
// ---------------------------------------------------------------------------

export type {
  PathData,
  FieldErrors,
  PathDefinition,
  PathEvent,
  PathSnapshot,
  PathStep,
  PathStepContext,
  ProgressLayout,
  RootProgress,
  SerializedPathState,
} from "@daltonr/pathwrite-core";

export { PathEngine } from "@daltonr/pathwrite-core";

// packages/react-adapter/src/index.ts
import {
  createContext,
  createElement,
  useCallback,
  useContext,
  useEffect,
  useRef,
  useSyncExternalStore
} from "react";
import type { PropsWithChildren, ReactElement, ReactNode } from "react";
import {
  PathData,
  PathDefinition,
  PathEngine,
  PathEvent,
  PathSnapshot,
  ProgressLayout,
  RootProgress
} from "@daltonr/pathwrite-core";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface UsePathOptions {
  /**
   * An externally-managed `PathEngine` to subscribe to — for example, the engine
   * returned by `createPersistedEngine()` from `@daltonr/pathwrite-store-http`.
   *
   * When provided:
   * - `usePath` will **not** create its own engine.
   * - The snapshot is seeded immediately from the engine's current state.
   * - The engine lifecycle (start / cleanup) is the **caller's responsibility**.
   * - `PathShell` will skip its own `autoStart` call.
   */
  engine?: PathEngine;
  /** Called for every engine event (stateChanged, completed, cancelled, resumed). The callback ref is kept current — changing it does **not** re-subscribe to the engine. */
  onEvent?: (event: PathEvent) => void;
}

export interface UsePathReturn<TData extends PathData = PathData> {
  /** Current path snapshot, or `null` when no path is active. Triggers a React re-render on change. */
  snapshot: PathSnapshot<TData> | null;
  /** Start (or restart) a path. */
  start: (path: PathDefinition<any>, initialData?: PathData) => void;
  /** Push a sub-path onto the stack. Requires an active path. Pass an optional `meta` object for correlation — it is returned unchanged to the parent step's `onSubPathComplete` / `onSubPathCancel` hooks. */
  startSubPath: (path: PathDefinition<any>, initialData?: PathData, meta?: Record<string, unknown>) => void;
  /** Advance one step. Completes the path on the last step. */
  next: () => void;
  /** Go back one step. No-op when already on the first step of a top-level path. Pops back to the parent path when on the first step of a sub-path. */
  previous: () => void;
  /** Cancel the active path (or sub-path). */
  cancel: () => void;
  /** Jump directly to a step by ID. Calls onLeave / onEnter but bypasses guards and shouldSkip. */
  goToStep: (stepId: string) => void;
  /** Jump directly to a step by ID, checking the current step's canMoveNext (forward) or canMovePrevious (backward) guard first. Navigation is blocked if the guard returns false. */
  goToStepChecked: (stepId: string) => void;
  /** Update a single data value; triggers a re-render via stateChanged. When `TData` is specified, `key` and `value` are type-checked against your data shape. */
  setData: <K extends string & keyof TData>(key: K, value: TData[K]) => void;
  /** Reset the current step's data to what it was when the step was entered. Useful for "Clear" or "Reset" buttons. */
  resetStep: () => void;
  /**
   * Tear down any active path (without firing hooks) and immediately start the
   * given path fresh. Safe to call whether or not a path is currently active.
   * Use for "Start over" / retry flows without remounting the component.
   */
  restart: (path: PathDefinition<any>, initialData?: PathData) => void;
}

export type PathProviderProps = PropsWithChildren<{
  /** Forwarded to the internal usePath hook. */
  onEvent?: (event: PathEvent) => void;
}>;

// ---------------------------------------------------------------------------
// usePath hook
// ---------------------------------------------------------------------------

export function usePath<TData extends PathData = PathData>(options?: UsePathOptions): UsePathReturn<TData> {
  // Use provided engine or create a stable new one for this hook's lifetime.
  // options.engine must be a stable reference (don't recreate on every render).
  const engineRef = useRef<PathEngine | null>(null);
  if (engineRef.current === null) {
    engineRef.current = options?.engine ?? new PathEngine();
  }
  const engine = engineRef.current;

  // Keep the onEvent callback current without changing the subscribe identity
  const onEventRef = useRef(options?.onEvent);
  onEventRef.current = options?.onEvent;

  // Seed immediately from existing engine state — essential when restoring a
  // persisted path (the engine is already started before usePath is called).
  // We track whether we've seeded to avoid calling engine.snapshot() on every
  // re-render (React evaluates useRef's argument each time).
  const seededRef = useRef(false);
  const snapshotRef = useRef<PathSnapshot<TData> | null>(null);
  if (!seededRef.current) {
    seededRef.current = true;
    try {
      snapshotRef.current = engine.snapshot() as PathSnapshot<TData> | null;
    } catch {
      snapshotRef.current = null;
    }
  }

  const subscribe = useCallback(
    (callback: () => void) =>
      engine.subscribe((event: PathEvent) => {
        if (event.type === "stateChanged" || event.type === "resumed") {
          snapshotRef.current = event.snapshot as PathSnapshot<TData>;
        } else if (event.type === "completed" || event.type === "cancelled") {
          snapshotRef.current = null;
        }
        onEventRef.current?.(event);
        callback();
      }),
    [engine]
  );

  const getSnapshot = useCallback(() => snapshotRef.current, []);

  const snapshot = useSyncExternalStore(subscribe, getSnapshot);

  // Stable action callbacks
  const start = useCallback(
    (path: PathDefinition<any>, initialData: PathData = {}) =>
      engine.start(path, initialData),
    [engine]
  );

  const startSubPath = useCallback(
    (path: PathDefinition<any>, initialData: PathData = {}, meta?: Record<string, unknown>) =>
      engine.startSubPath(path, initialData, meta),
    [engine]
  );

  const next = useCallback(() => engine.next(), [engine]);
  const previous = useCallback(() => engine.previous(), [engine]);
  const cancel = useCallback(() => engine.cancel(), [engine]);

  const goToStep = useCallback(
    (stepId: string) => engine.goToStep(stepId),
    [engine]
  );

  const goToStepChecked = useCallback(
    (stepId: string) => engine.goToStepChecked(stepId),
    [engine]
  );

  const setData = useCallback(
    <K extends string & keyof TData>(key: K, value: TData[K]) => engine.setData(key, value as unknown),
    [engine]
  ) as UsePathReturn<TData>["setData"];

  const resetStep = useCallback(() => engine.resetStep(), [engine]);

  const restart = useCallback(
    (path: PathDefinition<any>, initialData: PathData = {}) =>
      engine.restart(path, initialData),
    [engine]
  );

  return { snapshot, start, startSubPath, next, previous, cancel, goToStep, goToStepChecked, setData, resetStep, restart };
}

// ---------------------------------------------------------------------------
// Context + Provider
// ---------------------------------------------------------------------------

const PathContext = createContext<UsePathReturn | null>(null);

/**
 * Provides a single `usePath` instance to all descendants.
 * Consume with `usePathContext()`.
 */
export function PathProvider({ children, onEvent }: PathProviderProps): ReactElement {
  const path = usePath({ onEvent });
  return createElement(PathContext.Provider, { value: path }, children);
}

/**
 * Access the nearest `PathProvider`'s path instance.
 * Throws if used outside of a `<PathProvider>`.
 *
 * The optional generic narrows `snapshot.data` for convenience — it is a
 * **type-level assertion**, not a runtime guarantee.
 */
export function usePathContext<TData extends PathData = PathData>(): UsePathReturn<TData> {
  const ctx = useContext(PathContext);
  if (ctx === null) {
    throw new Error("usePathContext must be used within a <PathProvider>.");
  }
  return ctx as UsePathReturn<TData>;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Converts a camelCase or lowercase field key to a display label.
 *  e.g. "firstName" → "First Name", "email" → "Email" */
function formatFieldKey(key: string): string {
  return key.replace(/([A-Z])/g, " $1").replace(/^./, c => c.toUpperCase()).trim();
}

// ---------------------------------------------------------------------------
// Default UI — PathShell
// ---------------------------------------------------------------------------

export interface PathShellProps {
  /** The path definition to drive. */
  path: PathDefinition<any>;
  /**
   * An externally-managed engine — for example, the engine returned by
   * `createPersistedEngine()`. When supplied, `PathShell` will skip its own
   * `start()` call and drive the UI from the provided engine instead.
   */
  engine?: PathEngine;
  /** Map of step ID → content. The shell renders `steps[snapshot.stepId]` for the current step. */
  steps: Record<string, ReactNode>;
  /** Initial data passed to `engine.start()`. */
  initialData?: PathData;
  /** If true, the path is started automatically on mount. Defaults to `true`. */
  autoStart?: boolean;
  /** Called when the path completes. Receives the final data. */
  onComplete?: (data: PathData) => void;
  /** Called when the path is cancelled. Receives the data at time of cancellation. */
  onCancel?: (data: PathData) => void;
  /** Called for every engine event. */
  onEvent?: (event: PathEvent) => void;
  /** Label for the Previous button. Defaults to `"Previous"`. */
  backLabel?: string;
  /** Label for the Next button. Defaults to `"Next"`. */
  nextLabel?: string;
  /** Label for the Complete button (shown on the last step). Defaults to `"Complete"`. */
  completeLabel?: string;
  /** Label for the Cancel button. Defaults to `"Cancel"`. */
  cancelLabel?: string;
  /** If true, hide the Cancel button. Defaults to `false`. */
  hideCancel?: boolean;
  /** If true, hide the progress indicator. Also hidden automatically when the path has only one step. Defaults to `false`. */
  hideProgress?: boolean;
  /**
   * Footer layout mode:
   * - `"auto"` (default): Uses "form" for single-step top-level paths, "wizard" otherwise.
   * - `"wizard"`: Back button on left, Cancel and Submit together on right.
   * - `"form"`: Cancel on left, Submit alone on right. Back button never shown.
   */
  footerLayout?: "wizard" | "form" | "auto";
  /** Optional extra CSS class on the root element. */
  className?: string;
  /** Render prop to replace the entire header (progress area). Receives the snapshot. */
  renderHeader?: (snapshot: PathSnapshot) => ReactNode;
  /** Render prop to replace the entire footer (navigation area). Receives the snapshot and actions. */
  renderFooter?: (snapshot: PathSnapshot, actions: PathShellActions) => ReactNode;
  /**
   * Controls whether the shell renders its auto-generated field-error summary box.
   * - `"summary"` (default): Shell renders the labeled error list below the step body.
   * - `"inline"`: Suppress the summary — handle errors inside the step template instead.
   * - `"both"`: Render the shell summary AND whatever the step template renders.
   */
  validationDisplay?: "summary" | "inline" | "both";
  /**
   * Controls how progress bars are arranged when a sub-path is active.
   * - `"merged"` (default): Root and sub-path bars in one card.
   * - `"split"`: Root and sub-path bars as separate cards.
   * - `"rootOnly"`: Only the root bar — sub-path bar hidden.
   * - `"activeOnly"`: Only the active (sub-path) bar — root bar hidden.
   */
  progressLayout?: ProgressLayout;
}

export interface PathShellActions {
  next: () => void;
  previous: () => void;
  cancel: () => void;
  goToStep: (stepId: string) => void;
  goToStepChecked: (stepId: string) => void;
  setData: (key: string, value: unknown) => void;
  /** Restart the shell's current path with its current `initialData`. */
  restart: () => void;
}

/**
 * Default UI shell that renders a progress indicator, step content, and navigation
 * buttons. Pass a `steps` map to define per-step content.
 *
 * ```tsx
 * <PathShell
 *   path={myPath}
 *   initialData={{ name: "" }}
 *   onComplete={handleDone}
 *   steps={{
 *     details: <DetailsForm />,
 *     review: <ReviewPanel />,
 *   }}
 * />
 * ```
 */
export function PathShell({
  path: pathDef,
  engine: externalEngine,
  steps,
  initialData = {},
  autoStart = true,
  onComplete,
  onCancel,
  onEvent,
  backLabel = "Previous",
  nextLabel = "Next",
  completeLabel = "Complete",
  cancelLabel = "Cancel",
  hideCancel = false,
  hideProgress = false,
  footerLayout = "auto",
  className,
  renderHeader,
  renderFooter,
  validationDisplay = "inline",
  progressLayout = "merged",
}: PathShellProps): ReactElement {
  const pathReturn = usePath({
    engine: externalEngine,
    onEvent(event) {
      onEvent?.(event);
      if (event.type === "completed") onComplete?.(event.data);
      if (event.type === "cancelled") onCancel?.(event.data);
    }
  });

  const { snapshot, start, next, previous, cancel, goToStep, goToStepChecked, setData, restart } = pathReturn;

  // Auto-start on mount — skipped when an external engine is provided since
  // the caller is responsible for starting it (e.g. via createPersistedEngine).
  const startedRef = useRef(false);
  useEffect(() => {
    if (autoStart && !startedRef.current && !externalEngine) {
      startedRef.current = true;
      start(pathDef, initialData);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Look up step content from the steps map
  const stepContent = snapshot ? (steps[snapshot.stepId] ?? null) : null;

  if (!snapshot) {
    return createElement(PathContext.Provider, { value: pathReturn },
      createElement("div", { className: cls("pw-shell", className) },
        createElement("div", { className: "pw-shell__empty" },
          createElement("p", null, "No active path."),
          !autoStart && createElement("button", {
            type: "button",
            className: "pw-shell__start-btn",
            onClick: () => start(pathDef, initialData)
          }, "Start")
        )
      )
    );
  }

  const actions: PathShellActions = {
    next, previous, cancel, goToStep, goToStepChecked, setData,
    restart: () => restart(pathDef, initialData)
  };

  const showRoot = !hideProgress && !!snapshot.rootProgress && progressLayout !== "activeOnly";
  const showActive = !hideProgress && (renderHeader
    ? true
    : (snapshot.stepCount > 1 || snapshot.nestingLevel > 0) && progressLayout !== "rootOnly");

  return createElement(PathContext.Provider, { value: pathReturn },
    createElement("div", { className: cls("pw-shell", progressLayout !== "merged" && `pw-shell--progress-${progressLayout}`, className) },
      // Root progress — persistent top-level bar visible during sub-paths
      showRoot && defaultRootProgress(snapshot.rootProgress!),
      // Header — progress indicator (active path)
      showActive && (renderHeader
        ? renderHeader(snapshot)
        : (snapshot.stepCount > 1 || snapshot.nestingLevel > 0) && defaultHeader(snapshot)),
      // Body — step content
      createElement("div", { className: "pw-shell__body" }, stepContent),
      // Validation messages — suppressed when validationDisplay="inline"
      validationDisplay !== "inline" && snapshot.hasAttemptedNext && Object.keys(snapshot.fieldMessages).length > 0 && createElement("ul", { className: "pw-shell__validation" },
        ...Object.entries(snapshot.fieldMessages).map(([key, msg]) =>
          createElement("li", { key, className: "pw-shell__validation-item" },
            key !== "_" && createElement("span", { className: "pw-shell__validation-label" }, formatFieldKey(key)),
            msg
          )
        )
      ),
      // Warning messages — non-blocking, shown immediately (no hasAttemptedNext gate)
      validationDisplay !== "inline" && Object.keys(snapshot.fieldWarnings).length > 0 && createElement("ul", { className: "pw-shell__warnings" },
        ...Object.entries(snapshot.fieldWarnings).map(([key, msg]) =>
          createElement("li", { key, className: "pw-shell__warnings-item" },
            key !== "_" && createElement("span", { className: "pw-shell__warnings-label" }, formatFieldKey(key)),
            msg
          )
        )
      ),
      // Footer — navigation buttons
      renderFooter
        ? renderFooter(snapshot, actions)
        : defaultFooter(snapshot, actions, {
            backLabel, nextLabel, completeLabel, cancelLabel, hideCancel, footerLayout
          })
    )
  );
}

// ---------------------------------------------------------------------------
// Root progress (compact top-level bar visible during sub-paths)
// ---------------------------------------------------------------------------

function defaultRootProgress(root: RootProgress): ReactElement {
  return createElement("div", { className: "pw-shell__root-progress" },
    createElement("div", { className: "pw-shell__steps" },
      ...root.steps.map((step, i) =>
        createElement("div", {
          key: step.id,
          className: cls("pw-shell__step", `pw-shell__step--${step.status}`)
        },
          createElement("span", { className: "pw-shell__step-dot" },
            step.status === "completed" ? "✓" : String(i + 1)
          ),
          createElement("span", { className: "pw-shell__step-label" },
            step.title ?? step.id
          )
        )
      )
    ),
    createElement("div", { className: "pw-shell__track" },
      createElement("div", {
        className: "pw-shell__track-fill",
        style: { width: `${root.progress * 100}%` }
      })
    )
  );
}

// ---------------------------------------------------------------------------
// Default header (progress indicator)
// ---------------------------------------------------------------------------

function defaultHeader(snapshot: PathSnapshot): ReactElement {
  return createElement("div", { className: "pw-shell__header" },
    createElement("div", { className: "pw-shell__steps" },
      ...snapshot.steps.map((step, i) =>
        createElement("div", {
          key: step.id,
          className: cls("pw-shell__step", `pw-shell__step--${step.status}`)
        },
          createElement("span", { className: "pw-shell__step-dot" },
            step.status === "completed" ? "✓" : String(i + 1)
          ),
          createElement("span", { className: "pw-shell__step-label" },
            step.title ?? step.id
          )
        )
      )
    ),
    createElement("div", { className: "pw-shell__track" },
      createElement("div", {
        className: "pw-shell__track-fill",
        style: { width: `${snapshot.progress * 100}%` }
      })
    )
  );
}

// ---------------------------------------------------------------------------
// Default footer (navigation buttons)
// ---------------------------------------------------------------------------

interface FooterLabels {
  backLabel: string;
  nextLabel: string;
  completeLabel: string;
  cancelLabel: string;
  hideCancel: boolean;
  footerLayout: "wizard" | "form" | "auto";
}

function defaultFooter(
  snapshot: PathSnapshot,
  actions: PathShellActions,
  labels: FooterLabels
): ReactElement {
  // Auto-detect layout: single-step top-level paths use "form", everything else uses "wizard"
  const resolvedLayout = labels.footerLayout === "auto"
    ? (snapshot.stepCount === 1 && snapshot.nestingLevel === 0 ? "form" : "wizard")
    : labels.footerLayout;
  
  const isFormMode = resolvedLayout === "form";
  
  return createElement("div", { className: "pw-shell__footer" },
    createElement("div", { className: "pw-shell__footer-left" },
      // Form mode: Cancel on the left
      isFormMode && !labels.hideCancel && createElement("button", {
        type: "button",
        className: "pw-shell__btn pw-shell__btn--cancel",
        disabled: snapshot.isNavigating,
        onClick: actions.cancel
      }, labels.cancelLabel),
      // Wizard mode: Back on the left
      !isFormMode && !snapshot.isFirstStep && createElement("button", {
        type: "button",
        className: "pw-shell__btn pw-shell__btn--back",
        disabled: snapshot.isNavigating || !snapshot.canMovePrevious,
        onClick: actions.previous
      }, labels.backLabel)
    ),
    createElement("div", { className: "pw-shell__footer-right" },
      // Wizard mode: Cancel on the right
      !isFormMode && !labels.hideCancel && createElement("button", {
        type: "button",
        className: "pw-shell__btn pw-shell__btn--cancel",
        disabled: snapshot.isNavigating,
        onClick: actions.cancel
      }, labels.cancelLabel),
      // Both modes: Submit on the right
      createElement("button", {
        type: "button",
        className: "pw-shell__btn pw-shell__btn--next",
        disabled: snapshot.isNavigating,
        onClick: actions.next
      }, snapshot.isLastStep ? labels.completeLabel : labels.nextLabel)
    )
  );
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function cls(...parts: (string | undefined | false | null)[]): string {
  return parts.filter(Boolean).join(" ");
}

// ---------------------------------------------------------------------------
// Re-export core types for convenience
// ---------------------------------------------------------------------------

export type {
  PathData,
  FieldErrors,
  PathDefinition,
  PathEvent,
  PathSnapshot,
  PathStep,
  PathStepContext,
  ProgressLayout,
  RootProgress,
  SerializedPathState
} from "@daltonr/pathwrite-core";

export { PathEngine } from "@daltonr/pathwrite-core";
