// apps/react-demos/demo-react-subwizard/src/CreateDocumentStep.tsx
import { usePathContext } from "@daltonr/pathwrite-react";
import type { DocumentData } from "./types";

export function CreateDocumentStep() {
  const { snapshot, setData } = usePathContext<DocumentData>();
  const snap = snapshot!;
  const data = snap.data;
  const errors = snap.hasAttemptedNext ? snap.fieldErrors : {};

  return (
    <div className="form-body">
      <p className="step-intro">Enter the details of the document you want to send for approval.</p>

      <div className={`field ${errors.title ? "field--error" : ""}`}>
        <label htmlFor="title">
          Title <span className="required">*</span>
        </label>
        <input
          id="title"
          type="text"
          value={data.title ?? ""}
          autoFocus
          onChange={(e) => setData("title", e.target.value)}
          placeholder="e.g. Q1 Budget Report"
          autoComplete="off"
        />
        {errors.title && <span className="field-error">{errors.title}</span>}
      </div>

      <div className={`field ${errors.description ? "field--error" : ""}`}>
        <label htmlFor="description">
          Description <span className="required">*</span>
        </label>
        <textarea
          id="description"
          value={data.description ?? ""}
          rows={4}
          onChange={(e) => setData("description", e.target.value)}
          placeholder="Brief summary of the document and what needs to be approved..."
        />
        {errors.description && <span className="field-error">{errors.description}</span>}
      </div>
    </div>
  );
}

// apps/vue-demos/demo-vue-subwizard/src/CreateDocumentStep.vue
<script setup lang="ts">
import { computed } from "vue";
import { usePathContext } from "@daltonr/pathwrite-vue";
import type { DocumentData } from "./types";

const { snapshot, setData } = usePathContext<DocumentData>();
const data = computed(() => snapshot.value?.data);
const errors = computed(() => snapshot.value?.fieldErrors ?? {});
const attempted = computed(() => snapshot.value?.hasAttemptedNext ?? false);
</script>

<template>
  <div class="form-body">
    <p class="step-intro">Enter the details of the document you want to send for approval.</p>

    <div :class="['field', attempted && errors.title ? 'field--error' : '']">
      <label for="title">Title <span class="required">*</span></label>
      <input
        id="title"
        type="text"
        :value="data?.title"
        @input="setData('title', ($event.target as HTMLInputElement).value)"
        placeholder="e.g. Q1 Budget Report"
        autofocus
        autocomplete="off"
      />
      <span v-if="attempted && errors.title" class="field-error">{{ errors.title }}</span>
    </div>

    <div :class="['field', attempted && errors.description ? 'field--error' : '']">
      <label for="description">Description <span class="required">*</span></label>
      <textarea
        id="description"
        :value="data?.description"
        @input="setData('description', ($event.target as HTMLTextAreaElement).value)"
        placeholder="Brief summary of the document and what needs to be approved..."
        rows="4"
      />
      <span v-if="attempted && errors.description" class="field-error">{{ errors.description }}</span>
    </div>
  </div>
</template>
