// apps/react-demos/demo-react-subwizard/src/DecisionStep.tsx
import { usePathContext } from "@daltonr/pathwrite-react";
import type { ApprovalData } from "./types";

export function DecisionStep() {
  const { snapshot, setData } = usePathContext<ApprovalData>();
  const snap   = snapshot!;
  const data   = snap.data;
  const errors = snap.hasAttemptedNext ? snap.fieldMessages : {};

  return (
    <div className="form-body">
      <p className="step-intro">
        You are reviewing <strong>{data.documentTitle as string}</strong> as <strong>{data.approverName as string}</strong>.
      </p>

      <div>
        <p className="pref-label">Your Decision <span className="required">*</span></p>
        <div className="radio-group">
          <label className={`radio-option ${data.decision === "approved" ? "radio-option--approved" : ""}`}>
            <input type="radio" name="decision" value="approved"
              checked={data.decision === "approved"}
              onChange={() => setData("decision", "approved")} />
            <span className="radio-option-label">✓ Approve</span>
            <span className="radio-option-desc">The document is ready to proceed.</span>
          </label>
          <label className={`radio-option ${data.decision === "rejected" ? "radio-option--rejected" : ""}`}>
            <input type="radio" name="decision" value="rejected"
              checked={data.decision === "rejected"}
              onChange={() => setData("decision", "rejected")} />
            <span className="radio-option-label">✗ Reject</span>
            <span className="radio-option-desc">Changes are required before this can proceed.</span>
          </label>
        </div>
        {errors.decision && <span className="field-error">{errors.decision}</span>}
      </div>

      <div className="field">
        <label htmlFor="comment">Comment <span className="optional">(optional)</span></label>
        <textarea id="comment" value={data.comment ?? ""} rows={3}
          onChange={e => setData("comment", e.target.value)}
          placeholder="Add any notes or feedback for the document author..." />
      </div>
    </div>
  );
}

// apps/vue-demos/demo-vue-subwizard/src/DecisionStep.vue
<script setup lang="ts">
import { computed } from "vue";
import { usePathContext } from "@daltonr/pathwrite-vue";
import type { ApprovalData } from "./types";

const { snapshot, setData } = usePathContext<ApprovalData>();
const data      = computed(() => snapshot.value?.data);
const errors    = computed(() => snapshot.value?.fieldMessages ?? {});
const attempted  = computed(() => snapshot.value?.hasAttemptedNext ?? false);
</script>

<template>
  <div class="form-body">
    <p class="step-intro">
      You are reviewing <strong>{{ data?.documentTitle }}</strong> as <strong>{{ data?.approverName }}</strong>.
    </p>

    <!-- Approve / Reject -->
    <div>
      <p class="pref-label">Your Decision <span class="required">*</span></p>
      <div class="radio-group">
        <label :class="['radio-option', data?.decision === 'approved' ? 'radio-option--approved' : '']">
          <input
            type="radio"
            name="decision"
            value="approved"
            :checked="data?.decision === 'approved'"
            @change="setData('decision', 'approved')"
          />
          <span class="radio-option-label">✓ Approve</span>
          <span class="radio-option-desc">The document is ready to proceed.</span>
        </label>
        <label :class="['radio-option', data?.decision === 'rejected' ? 'radio-option--rejected' : '']">
          <input
            type="radio"
            name="decision"
            value="rejected"
            :checked="data?.decision === 'rejected'"
            @change="setData('decision', 'rejected')"
          />
          <span class="radio-option-label">✗ Reject</span>
          <span class="radio-option-desc">Changes are required before this can proceed.</span>
        </label>
      </div>
      <span v-if="attempted && errors.decision" class="field-error">{{ errors.decision }}</span>
    </div>

    <!-- Comment -->
    <div class="field">
      <label for="comment">Comment <span class="optional">(optional)</span></label>
      <textarea
        id="comment"
        :value="data?.comment"
        @input="setData('comment', ($event.target as HTMLTextAreaElement).value)"
        placeholder="Add any notes or feedback for the document author..."
        rows="3"
      />
    </div>
  </div>
</template>
