// apps/react-demos/demo-react-storage/src/SummaryStep.tsx
import { usePathContext } from "@daltonr/pathwrite-react";
import type { WizardData, Person, MemberProfile } from "./wizard";

function formatDate(d: string): string {
  if (!d) return "—";
  try {
    return new Date(d).toLocaleDateString("en-IE", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });
  } catch {
    return d;
  }
}

export function SummaryStep() {
  const { snapshot } = usePathContext<WizardData>();
  const data     = snapshot!.data;
  const members  = (data.members ?? []) as Person[];
  const profiles = (data.profiles ?? {}) as Record<string, MemberProfile>;

  return (
    <div className="form-body">
      <p className="step-intro">
        Review all team member profiles before submitting. Everything looks good? Click{" "}
        <strong>Submit Onboarding</strong>.
      </p>

      <div className="review-section">
        <p className="section-title">Team</p>
        <div className="review-card">
          <div className="review-row">
            <span className="review-key">Team Name</span>
            <span>{data.teamName as string}</span>
          </div>
          <div className="review-row">
            <span className="review-key">Members</span>
            <span>{members.length}</span>
          </div>
        </div>
      </div>

      {members.map((member, i) => {
        const profile = profiles[String(i)];
        return (
          <div key={i} className="review-section">
            <p className="section-title">
              {member.name}
              {member.role && <span className="section-title-sub"> — {member.role}</span>}
            </p>
            {profile ? (
              <div className="review-card">
                <div className="review-row">
                  <span className="review-key">Department</span>
                  <span>{profile.department}</span>
                </div>
                <div className="review-row">
                  <span className="review-key">Start Date</span>
                  <span>{formatDate(profile.startDate)}</span>
                </div>
                <div className="review-row">
                  <span className="review-key">Bio</span>
                  <span>{profile.bio}</span>
                </div>
                <div className="review-row">
                  <span className="review-key">30-Day Goals</span>
                  <span>{profile.goals30}</span>
                </div>
                <div className="review-row">
                  <span className="review-key">90-Day Goals</span>
                  <span>{profile.goals90}</span>
                </div>
              </div>
            ) : (
              <div className="review-card">
                <div className="review-row">
                  <span className="review-key">Profile</span>
                  <span className="text-pending">Not completed</span>
                </div>
              </div>
            )}
          </div>
        );
      })}
    </div>
  );
}

// apps/vue-demos/demo-vue-storage/src/SummaryStep.vue
<script setup lang="ts">
import { computed } from "vue";
import { usePathContext } from "@daltonr/pathwrite-vue";
import type { WizardData, Person, MemberProfile } from "./wizard";

const { snapshot } = usePathContext<WizardData>();

const data = computed(() => snapshot.value?.data);
const members = computed(() => (data.value?.members ?? []) as Person[]);
const profiles = computed(() => (data.value?.profiles ?? {}) as Record<string, MemberProfile>);

function getProfile(index: number): MemberProfile | null {
  return profiles.value[String(index)] ?? null;
}

function formatDate(d: string): string {
  if (!d) return "—";
  try {
    return new Date(d).toLocaleDateString("en-IE", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });
  } catch {
    return d;
  }
}
</script>

<template>
  <div class="form-body">
    <p class="step-intro">
      Review everything before submitting. Click <strong>Previous</strong> to go back and make changes.
    </p>

    <!-- Team header -->
    <div class="summary-team-card">
      <span class="summary-team-icon">🏢</span>
      <div>
        <p class="summary-team-name">{{ data?.teamName }}</p>
        <p class="summary-team-meta">{{ members.length }} member{{ members.length !== 1 ? "s" : "" }}</p>
      </div>
    </div>

    <!-- Per-member cards -->
    <div v-for="(member, i) in members" :key="i" class="summary-member-card">
      <div class="summary-member-header">
        <span class="member-avatar member-avatar--lg">{{ member.name.charAt(0).toUpperCase() }}</span>
        <div>
          <p class="summary-member-name">{{ member.name }}</p>
          <p v-if="member.role" class="summary-member-role">{{ member.role }}</p>
        </div>
      </div>

      <template v-if="getProfile(i)">
        <div class="summary-detail-grid">
          <span class="summary-key">Department</span>
          <span>{{ getProfile(i)!.department }}</span>
          <span class="summary-key">Start Date</span>
          <span>{{ formatDate(getProfile(i)!.startDate) }}</span>
        </div>

        <div class="summary-longtext-block">
          <p class="summary-longtext-label">Bio</p>
          <p class="summary-longtext-body">{{ getProfile(i)!.bio }}</p>
        </div>

        <div class="summary-goals-grid">
          <div class="summary-goal-block">
            <p class="summary-goal-label">🗓 30-Day Goals</p>
            <p class="summary-longtext-body">{{ getProfile(i)!.goals30 }}</p>
          </div>
          <div class="summary-goal-block">
            <p class="summary-goal-label">📈 90-Day Goals</p>
            <p class="summary-longtext-body">{{ getProfile(i)!.goals90 }}</p>
          </div>
        </div>
      </template>
    </div>
  </div>
</template>
