// apps/react-demos/demo-react-storage/src/TeamSetupStep.tsx
import { usePathContext } from "@daltonr/pathwrite-react";
import type { WizardData, Person } from "./wizard";

export function TeamSetupStep() {
  const { snapshot, setData } = usePathContext<WizardData>();
  const snap = snapshot!;
  const data = snap.data;
  const errors = snap.hasAttemptedNext ? snap.fieldErrors : {};
  const members = (data.members ?? []) as Person[];
  const teamName = (data.teamName ?? "") as string;

  function updateTeamName(value: string) {
    setData("teamName", value);
  }

  function addMember() {
    setData("members", [...members, { name: "", role: "" }]);
  }

  function removeMember(index: number) {
    setData(
      "members",
      members.filter((_, i) => i !== index)
    );
  }

  function updateMemberName(index: number, value: string) {
    setData(
      "members",
      members.map((m, i) => (i === index ? { ...m, name: value } : m))
    );
  }

  function updateMemberRole(index: number, value: string) {
    setData(
      "members",
      members.map((m, i) => (i === index ? { ...m, role: value } : m))
    );
  }

  return (
    <div className="form-body">
      <p className="step-intro">
        Enter your team's name and add everyone you'll be onboarding. You'll fill in a detailed profile for
        each person on the next step.
      </p>

      {/* Team name */}
      <div className={`field ${errors.teamName ? "field--error" : ""}`}>
        <label htmlFor="team-name">
          Team Name <span className="required">*</span>
        </label>
        <input
          id="team-name"
          type="text"
          placeholder="e.g. Platform Engineering"
          value={teamName}
          onChange={(e) => updateTeamName(e.target.value)}
          autoFocus
        />
        {errors.teamName && <span className="field-error">{errors.teamName}</span>}
      </div>

      {/* Members list */}
      <div>
        <div className="members-header">
          <p className="section-label">
            Team Members <span className="required">*</span>
          </p>
          <button type="button" className="btn-add" onClick={addMember}>
            + Add Member
          </button>
        </div>

        {members.length === 0 ? (
          <div className="empty-members">
            <span className="empty-members__icon">👥</span>
            <p>
              No members yet. Click <strong>+ Add Member</strong> to get started.
            </p>
          </div>
        ) : (
          <div className="member-list">
            {members.map((member, i) => (
              <div key={i} className="member-row">
                <span className="member-number">{i + 1}</span>
                <div className="member-fields">
                  <input
                    type="text"
                    placeholder="Full name *"
                    value={member.name}
                    onChange={(e) => updateMemberName(i, e.target.value)}
                    className={`member-name-input ${errors.members && snap.hasAttemptedNext && !member.name.trim() ? "input--error" : ""}`}
                  />
                  <input
                    type="text"
                    placeholder="Role / title (optional)"
                    value={member.role}
                    onChange={(e) => updateMemberRole(i, e.target.value)}
                    className="member-role-input"
                  />
                </div>
                <button
                  type="button"
                  className="btn-remove"
                  onClick={() => removeMember(i)}
                  title="Remove member"
                >
                  ✕
                </button>
              </div>
            ))}
          </div>
        )}

        {errors.members && <span className="field-error">{errors.members}</span>}
      </div>
    </div>
  );
}

// apps/vue-demos/demo-vue-storage/src/TeamSetupStep.vue
<script setup lang="ts">
import { computed } from "vue";
import { usePathContext } from "@daltonr/pathwrite-vue";
import type { WizardData, Person } from "./wizard";

const { snapshot, setData } = usePathContext<WizardData>();

const teamName = computed(() => (snapshot.value?.data.teamName as string) ?? "");
const members  = computed(() => (snapshot.value?.data.members  ?? []) as Person[]);
const errors   = computed(() => snapshot.value?.fieldErrors ?? {});
const attempted = computed(() => snapshot.value?.hasAttemptedNext ?? false);

function updateTeamName(value: string) {
  setData("teamName", value);
}

function addMember() {
  setData("members", [...members.value, { name: "", role: "" }]);
}

function removeMember(index: number) {
  setData("members", members.value.filter((_, i) => i !== index));
}

function updateMemberName(index: number, value: string) {
  setData("members", members.value.map((m, i) => i === index ? { ...m, name: value } : m));
}

function updateMemberRole(index: number, value: string) {
  setData("members", members.value.map((m, i) => i === index ? { ...m, role: value } : m));
}
</script>

<template>
  <div class="form-body">
    <p class="step-intro">
      Enter your team's name and add everyone you'll be onboarding. You'll fill in a detailed
      profile for each person on the next step.
    </p>

    <!-- Team name -->
    <div class="field" :class="{ 'field--error': attempted && errors.teamName }">
      <label for="team-name">
        Team Name <span class="required">*</span>
      </label>
      <input
        id="team-name"
        type="text"
        placeholder="e.g. Platform Engineering"
        :value="teamName"
        @input="updateTeamName(($event.target as HTMLInputElement).value)"
      />
      <p v-if="attempted && errors.teamName" class="field-error">{{ errors.teamName }}</p>
    </div>

    <!-- Members list -->
    <div>
      <div class="members-header">
        <p class="section-label">Team Members <span class="required">*</span></p>
        <button type="button" class="btn-add" @click="addMember">+ Add Member</button>
      </div>

      <div v-if="members.length === 0" class="empty-members">
        <span class="empty-members__icon">👥</span>
        <p>No members yet. Click <strong>+ Add Member</strong> to get started.</p>
      </div>

      <div class="member-list">
        <div v-for="(member, i) in members" :key="i" class="member-row">
          <span class="member-number">{{ i + 1 }}</span>
          <div class="member-fields">
            <input
              type="text"
              placeholder="Full name *"
              :value="member.name"
              @input="updateMemberName(i, ($event.target as HTMLInputElement).value)"
              class="member-name-input"
              :class="{ 'input--error': attempted && !member.name.trim() }"
            />
            <input
              type="text"
              placeholder="Role / title (optional)"
              :value="member.role"
              @input="updateMemberRole(i, ($event.target as HTMLInputElement).value)"
              class="member-role-input"
            />
          </div>
          <button
            type="button"
            class="btn-remove"
            @click="removeMember(i)"
            title="Remove member"
          >✕</button>
        </div>
      </div>

      <p v-if="attempted && errors.members" class="field-error">{{ errors.members }}</p>
    </div>
  </div>
</template>
