// apps/vue-demos/demo-vue-subwizard/src/SelectApproversStep.vue
<script setup lang="ts">
import { computed } from "vue";
import { usePathContext } from "@daltonr/pathwrite-vue";
import { AVAILABLE_APPROVERS } from "./approval";
import type { DocumentData } from "./types";

const { snapshot, setData } = usePathContext<DocumentData>();
const data     = computed(() => snapshot.value?.data);
const errors   = computed(() => snapshot.value?.fieldMessages ?? {});
const attempted = computed(() => snapshot.value?.hasAttemptedNext ?? false);

function toggleApprover(id: string) {
  const current = (data.value?.approvers ?? []) as string[];
  const updated  = current.includes(id)
    ? current.filter(a => a !== id)
    : [...current, id];
  setData("approvers", updated);
}

function isSelected(id: string) {
  return ((data.value?.approvers ?? []) as string[]).includes(id);
}
</script>

<template>
  <div class="form-body">
    <p class="step-intro">Choose who needs to approve this document. All selected approvers must review before the workflow can proceed.</p>

    <div>
      <p class="pref-label">Available Approvers</p>
      <div class="approver-select-list">
        <label
          v-for="approver in AVAILABLE_APPROVERS"
          :key="approver.id"
          :class="['approver-select-item', isSelected(approver.id) ? 'approver-select-item--selected' : '']"
        >
          <input
            type="checkbox"
            :checked="isSelected(approver.id)"
            @change="toggleApprover(approver.id)"
          />
          <span class="approver-avatar">{{ approver.name.charAt(0) }}</span>
          <span class="approver-name">{{ approver.name }}</span>
        </label>
      </div>
      <span v-if="attempted && errors.approvers" class="field-error">{{ errors.approvers }}</span>
    </div>

    <p v-if="data?.approvers?.length" class="selection-count">
      {{ (data.approvers as string[]).length }} approver{{ (data.approvers as string[]).length !== 1 ? 's' : '' }} selected
    </p>
  </div>
</template>

// apps/react-demos/demo-react-subwizard/src/SelectApproversStep.tsx
import { usePathContext } from "@daltonr/pathwrite-react";
import { AVAILABLE_APPROVERS } from "./approval";
import type { DocumentData } from "./types";

export function SelectApproversStep() {
  const { snapshot, setData } = usePathContext<DocumentData>();
  const snap    = snapshot!;
  const data    = snap.data;
  const errors  = snap.hasAttemptedNext ? snap.fieldMessages : {};
  const selected = (data.approvers ?? []) as string[];

  function toggle(id: string) {
    const updated = selected.includes(id)
      ? selected.filter(a => a !== id)
      : [...selected, id];
    setData("approvers", updated);
  }

  return (
    <div className="form-body">
      <p className="step-intro">Choose who needs to approve this document. All selected approvers must review before the workflow can proceed.</p>

      <div>
        <p className="pref-label">Available Approvers</p>
        <div className="approver-select-list">
          {AVAILABLE_APPROVERS.map(approver => (
            <label key={approver.id}
              className={`approver-select-item ${selected.includes(approver.id) ? "approver-select-item--selected" : ""}`}>
              <input type="checkbox" checked={selected.includes(approver.id)} onChange={() => toggle(approver.id)} />
              <span className="approver-avatar">{approver.name.charAt(0)}</span>
              <span className="approver-name">{approver.name}</span>
            </label>
          ))}
        </div>
        {errors.approvers && <span className="field-error">{errors.approvers}</span>}
      </div>

      {selected.length > 0 && (
        <p className="selection-count">{selected.length} approver{selected.length !== 1 ? "s" : ""} selected</p>
      )}
    </div>
  );
}
