// apps/svelte-demos/demo-svelte-subwizard/src/ViewDocumentStep.svelte
<script lang="ts">
  import { usePathContext } from "@daltonr/pathwrite-svelte";
  import type { ApprovalData } from "./types";

  const ctx = usePathContext<ApprovalData>();
</script>

{#if ctx.snapshot}
  <div class="form-body">
    <p class="step-intro">
      Reviewing as <strong>{ctx.snapshot.data.approverName}</strong>. Please read the document carefully before making your decision.
    </p>
    <div class="document-preview">
      <p class="document-preview__label">Document</p>
      <p class="document-preview__title">{ctx.snapshot.data.documentTitle}</p>
      <p class="document-preview__body">{ctx.snapshot.data.documentDescription}</p>
    </div>
    <p class="step-note">Click <strong>Next</strong> to record your decision, or <strong>Previous</strong> to return to the approvals list.</p>
  </div>
{/if}

// apps/react-demos/demo-react-subwizard/src/ViewDocumentStep.tsx
import { usePathContext } from "@daltonr/pathwrite-react";
import type { ApprovalData } from "./types";

export function ViewDocumentStep() {
  const { snapshot } = usePathContext<ApprovalData>();
  const data = snapshot!.data;

  return (
    <div className="form-body">
      <p className="step-intro">
        Reviewing as <strong>{data.approverName as string}</strong>. Please read the document carefully before
        making your decision.
      </p>
      <div className="document-preview">
        <p className="document-preview__label">Document</p>
        <p className="document-preview__title">{data.documentTitle as string}</p>
        <p className="document-preview__body">{data.documentDescription as string}</p>
      </div>
      <p className="step-note">
        Click <strong>Next</strong> to record your decision, or <strong>Previous</strong> to return to the
        approvals list.
      </p>
    </div>
  );
}
