// apps/vue-demos/demo-vue-nested/src/tabs/EquipmentTab.vue
<script setup lang="ts">
import { usePathContext } from "@daltonr/pathwrite-vue";
import type { EmployeeDetails } from "../employee-details";
import { LAPTOP_TYPES } from "../employee-details";
import TabBar from "./TabBar.vue";

const { snapshot, setData } = usePathContext<EmployeeDetails>();
</script>

<template>
  <div class="tab-content">
    <TabBar />
    <div class="form-body">
      <div class="field">
        <label for="laptopType">Laptop <span class="optional">(optional)</span></label>
        <select
          id="laptopType"
          :value="snapshot.data.laptopType ?? 'macbook-pro'"
          @change="setData('laptopType', ($event.target as HTMLSelectElement).value)"
        >
          <option v-for="l in LAPTOP_TYPES" :key="l.value" :value="l.value">{{ l.label }}</option>
        </select>
      </div>

      <div class="field">
        <label>Mobile Phone</label>
        <div class="radio-group">
          <label v-for="val in ['yes', 'no']" :key="val" class="radio-option">
            <input
              type="radio"
              name="needsPhone"
              :value="val"
              :checked="(snapshot.data.needsPhone ?? 'no') === val"
              @change="setData('needsPhone', val)"
            />
            <span class="radio-option-label">{{ val === 'yes' ? 'Provide a company phone' : 'No phone needed' }}</span>
          </label>
        </div>
      </div>

      <div class="field">
        <label>Access Card</label>
        <div class="radio-group">
          <label v-for="val in ['yes', 'no']" :key="val" class="radio-option">
            <input
              type="radio"
              name="needsAccessCard"
              :value="val"
              :checked="(snapshot.data.needsAccessCard ?? 'yes') === val"
              @change="setData('needsAccessCard', val)"
            />
            <span class="radio-option-label">{{ val === 'yes' ? 'Issue an access card' : 'No access card' }}</span>
          </label>
        </div>
      </div>

      <div class="field">
        <label for="otherEquipment">Other Equipment <span class="optional">(optional)</span></label>
        <input
          id="otherEquipment" type="text"
          :value="snapshot.data.otherEquipment ?? ''"
          @input="setData('otherEquipment', ($event.target as HTMLInputElement).value)"
          placeholder="e.g. standing desk, external monitor…"
        />
      </div>
    </div>
  </div>
</template>

// apps/react-demos/demo-react-nested/src/tabs/EquipmentTab.tsx
import { usePathContext } from "@daltonr/pathwrite-react";
import type { EmployeeDetails } from "../employee-details";
import { LAPTOP_TYPES } from "../employee-details";
import { TabBar } from "./TabBar";

export function EquipmentTab() {
  const { snapshot, setData } = usePathContext<EmployeeDetails>();
  if (!snapshot) return null;
  const data = snapshot.data;

  return (
    <div className="tab-content">
      <TabBar />
      <div className="form-body">
        <div className="field">
          <label htmlFor="laptopType">
            Laptop <span className="optional">(optional)</span>
          </label>
          <select
            id="laptopType"
            value={data.laptopType ?? "macbook-pro"}
            onChange={(e) => setData("laptopType", e.target.value)}
          >
            {LAPTOP_TYPES.map((l) => (
              <option key={l.value} value={l.value}>
                {l.label}
              </option>
            ))}
          </select>
        </div>

        <div className="field">
          <label>Mobile Phone</label>
          <div className="radio-group">
            {["yes", "no"].map((val) => (
              <label key={val} className="radio-option">
                <input
                  type="radio"
                  name="needsPhone"
                  value={val}
                  checked={(data.needsPhone ?? "no") === val}
                  onChange={() => setData("needsPhone", val)}
                />
                <span className="radio-option-label">
                  {val === "yes" ? "Provide a company phone" : "No phone needed"}
                </span>
              </label>
            ))}
          </div>
        </div>

        <div className="field">
          <label>Access Card</label>
          <div className="radio-group">
            {["yes", "no"].map((val) => (
              <label key={val} className="radio-option">
                <input
                  type="radio"
                  name="needsAccessCard"
                  value={val}
                  checked={(data.needsAccessCard ?? "yes") === val}
                  onChange={() => setData("needsAccessCard", val)}
                />
                <span className="radio-option-label">
                  {val === "yes" ? "Issue an access card" : "No access card"}
                </span>
              </label>
            ))}
          </div>
        </div>

        <div className="field">
          <label htmlFor="otherEquipment">
            Other Equipment <span className="optional">(optional)</span>
          </label>
          <input
            id="otherEquipment"
            type="text"
            value={data.otherEquipment ?? ""}
            onChange={(e) => setData("otherEquipment", e.target.value)}
            placeholder="e.g. standing desk, external monitor…"
          />
        </div>
      </div>
    </div>
  );
}
